export const _OWNERS = {
  "IBST": [{"n":"Pt Iforte Solusi Infot","t":"CP","p":99.95,"q":null}],
  "MFMI": [{"n":"Iron Mountain Hong Kon","t":"CP","p":99.35,"q":null}],
  "SMDM": [{"n":"Bumi Serpong Damai Tbk","t":"CP","p":98.97,"q":null}],
  "SCPI": [{"n":"Organon Llc","t":"CP","p":98.79,"q":null}],
  "SUPR": [{"n":"Pt Profesional Telekom","t":"CP","p":97.33,"q":null}],
  "META": [{"n":"Pt Metro Pacific Tollw","t":"CP","p":97.14,"q":null}],
  "PLIN": [{"n":"Pt Plaza Indonesia Inv","t":"CP","p":96.61,"q":null}],
  "ANJT": [{"n":"First Resources Limite","t":"CP","p":95.92,"q":null}],
  "WICO": [{"n":"Ctla Safekeeping Accou","t":"CP","p":95.5,"q":null}],
  "JAWA": [{"n":"Uob Kay Hian Pte Ltd A","t":"CP","p":92.5,"q":null}],
  "INRU": [{"n":"Allied Hill Limited","t":"CP","p":92.54,"q":null}],
  "SMAR": [{"n":"Pt Purimas Sasmita","t":"CP","p":92.4,"q":null}],
  "DUTI": [{"n":"Bumi Serpong Damai Tbk","t":"CP","p":92.38,"q":null}],
  "FPNI": [{"n":"Lotte Chemical Titan I","t":"CP","p":92.5,"q":null}],
  "AKSI": [{"n":"Pt Batulicin Enam Semb","t":"CP","p":92.46,"q":null}],
  "HMSP": [{"n":"Philip Morris Indonesi","t":"CP","p":92.44,"q":null}],
  "BABY": [{"n":"Blooming Years Pte.Ltd","t":"CP","p":92.35,"q":null}],
  "CENT": [{"n":"Ep Id Holdings Pte.Ltd","t":"CP","p":92.17,"q":null}],
  "DVLA": [{"n":"Blue Sphere Singapore ","t":"CP","p":92.12,"q":null}],
  "ERTX": [{"n":"Pt Ungaran Sari Garmen","t":"CP","p":92.19,"q":null}],
  "KIAS": [{"n":"Scg Decor Public Compa","t":"OT","p":92.04,"q":null}],
  "EPMT": [{"n":"Kalbe Farma Tbk Pt","t":"CP","p":91.98,"q":null}],
  "IMJS": [{"n":"Pt. Indomobil Sukses I","t":"CP","p":91.97,"q":null}],
  "BKSW": [{"n":"Qatar National Bank Q.","t":"IB","p":91.57,"q":null}],
  "AGRS": [{"n":"Industrial Bank Of Kor","t":"OT","p":91.49,"q":null}],
  "BDMN": [{"n":"Mufg Bank Ltd","t":"IB","p":91.47,"q":null}],
  "IKBI": [{"n":"Sumitomo Electric Indu","t":"CP","p":91.46,"q":null}],
  "MMLP": [{"n":"Saka Industrial Arjaya","t":"CP","p":91.44,"q":null}],
  "BNGA": [{"n":"Cimb Group Sdn Bhd","t":"IB","p":91.45,"q":null}],
  "ADES": [{"n":"Water Partners Bottlin","t":"CP","p":91.35,"q":null}],
  "ESTI": [{"n":"Cahaya Interkontinenta","t":"CP","p":91.21,"q":null}],
  "BTPN": [{"n":"Sumitomo Mitsui Bankin","t":"IB","p":91.05,"q":null}],
  "ACST": [{"n":"Pt. Karya Supra Perkas","t":"CP","p":91.17,"q":null}],
  "GIAA": [{"n":"Perusahaan Perseroan (","t":"CP","p":91.11,"q":null}],
  "BSWD": [{"n":"Bank Of India","t":"CP","p":90.96,"q":null}],
  "SDRA": [{"n":"Woori Bank","t":"IB","p":90.75,"q":null}],
  "SIPD": [{"n":"Great Giant Pineapple","t":"CP","p":90.78,"q":null}],
  "IPAC": [{"n":"Apac Investment 2 Pte ","t":"CP","p":90.6,"q":null}],
  "KOIN": [{"n":"Scg Distribution Compa","t":"CP","p":90.62,"q":null}],
  "DNAR": [{"n":"Ok Next Co.Ltd","t":"IB","p":90.51,"q":null}],
  "TALF": [{"n":"Pt Proinvestindo","t":"CP","p":90.41,"q":null}],
  "TSPC": [{"n":"Pt. Bogamulia Nagadi","t":"CP","p":90.5,"q":null}],
  "BPII": [{"n":"Malacca Trust Pte. Ltd","t":"CP","p":89.86,"q":null}],
  "WIKA": [{"n":"Perusahaan Perseroan (","t":"CP","p":90.11,"q":null}],
  "YUPI": [{"n":"Confectionery Consumer","t":"CP","p":90,"q":null}],
  "PSAB": [{"n":"Jimmy Budiarto","t":"ID","p":90,"q":null}],
  "ADCP": [{"n":"Adhi Karya Persero Tbk","t":"CP","p":90,"q":null}],
  "KAEF": [{"n":"Pt Bio Farma (Persero)","t":"CP","p":89.82,"q":null}],
  "GLOB": [{"n":"Trikomsel Oke TbkPt","t":"CP","p":89.69,"q":null}],
  "YPAS": [{"n":"Pt Hastagraha Bumipers","t":"CP","p":89.47,"q":null}],
  "BBMD": [{"n":"Mestika Benua Mas","t":"CP","p":89.44,"q":null}],
  "KOBX": [{"n":"Pt Kobexindo Investama","t":"CP","p":89.45,"q":null}],
  "BNLI": [{"n":"Bangkok Bank Public Co","t":"IB","p":89.12,"q":null}],
  "MLBI": [{"n":"Heineken International","t":"CP","p":89.32,"q":null}],
  "LPCK": [{"n":"Kemuning Satiatama Pt","t":"OT","p":89,"q":null}],
  "CAKK": [{"n":"Kobin Keramik Industri","t":"CP","p":88.64,"q":null}],
  "GOLF": [{"n":"Bali Pecatu Graha","t":"CP","p":88.49,"q":null}],
  "INDS": [{"n":"Indoprima Gemilang","t":"CP","p":88.11,"q":null}],
  "CMNT": [{"n":"Wh Investments Pte. Lt","t":"CP","p":87.37,"q":null}],
  "CBDK": [{"n":"Pantai Indah Kapuk Dua","t":"CP","p":87.27,"q":null}],
  "CEKA": [{"n":"Sentratama Niaga Indon","t":"CP","p":87.02,"q":null}],
  "ABDA": [{"n":"Oona Indonesia Pte Ltd","t":"IS","p":86.75,"q":null}],
  "AGRO": [{"n":"Pt Bank Rakyat Indones","t":"IB","p":86.85,"q":null}],
  "JARR": [{"n":"Eshan Agro Sentosa Pt","t":"OT","p":86.64,"q":null}],
  "BIMA": [{"n":"Golden Lestari Pt","t":"CP","p":86.57,"q":null}],
  "IDPR": [{"n":"Manuel  Djunako","t":"ID","p":86.26,"q":null}],
  "BMAS": [{"n":"Kasikorn Vision Financ","t":"CP","p":86.03,"q":null}],
  "MTWI": [{"n":"Pt. Batavia Prosperind","t":"CP","p":85.9,"q":null}],
  "BINO": [{"n":"Ruhong Holding Pte Ltd","t":"CP","p":85.68,"q":null}],
  "RELI": [{"n":"Reliance Capital Manag","t":"CP","p":85.65,"q":null}],
  "ADMR": [{"n":"Alamtri Resources Indo","t":"CP","p":85.45,"q":null}],
  "SURI": [{"n":"Hansen Jap","t":"ID","p":85.4,"q":null}],
  "HRME": [{"n":"Pt Wijaya Wisesa Realt","t":"CP","p":85.39,"q":null}],
  "MLPT": [{"n":"Pt. Multipolar Tbk","t":"CP","p":84.95,"q":null}],
  "GDYR": [{"n":"The Goodyear Tire & Ru","t":"OT","p":85,"q":null}],
  "NISP": [{"n":"Ocbc Overseas Investme","t":"CP","p":85.08,"q":null}],
  "VINS": [{"n":"Pt. Victoria Investama","t":"CP","p":84.93,"q":null}],
  "UNVR": [{"n":"Unilever Indonesia Tbk","t":"CP","p":84.99,"q":null}],
  "SMCB": [{"n":"Pt Semen Indonesia (Pe","t":"CP","p":83.52,"q":null}],
  "SAME": [{"n":"Pt Elang Mahkota Tekno","t":"CP","p":84.78,"q":null}],
  "GTSI": [{"n":"Humpuss Maritim Intern","t":"CP","p":84.8,"q":null}],
  "NELY": [{"n":"Haskojaya AbadiPt","t":"CP","p":83.83,"q":null}],
  "PANI": [{"n":"Multi Artha Pratama Pt","t":"CP","p":84.09,"q":null}],
  "CUAN": [{"n":"Prajogo Pangestu","t":"ID","p":84.1,"q":null}],
  "CAMP": [{"n":"Sabana Prawira Widjaja","t":"ID","p":83.94,"q":null}],
  "TRJA": [{"n":"Pt Samindo Resources T","t":"CP","p":83.81,"q":null}],
  "ALKA": [{"n":"Gesit Perkasa","t":"CP","p":83.79,"q":null}],
  "TMAS": [{"n":"Pt Temas Lestari","t":"CP","p":83.66,"q":null}],
  "MDIA": [{"n":"Pt Visi Media Asia Tbk","t":"CP","p":83.28,"q":null}],
  "OMED": [{"n":"Intisumber Hasilsempur","t":"CP","p":83.3,"q":null}],
  "IGAR": [{"n":"Pt Kingsford Holdings","t":"CP","p":83.22,"q":null}],
  "SMKL": [{"n":"Pt. Satyamitra Investi","t":"CP","p":83.06,"q":null}],
  "APLN": [{"n":"Indofica Pt","t":"CP","p":82.72,"q":null}],
  "ELPI": [{"n":"Kreasi Cipta Timur","t":"CP","p":82.36,"q":null}],
  "BPFI": [{"n":"Woori Card Co. Ltd.","t":"CP","p":82.03,"q":null}],
  "MBSS": [{"n":"Pt Galley Adhika Arnaw","t":"CP","p":82.5,"q":null}],
  "ARTA": [{"n":"Lucas Sh. Cn","t":"ID","p":82.13,"q":null}],
  "EKAD": [{"n":"Pt. Ekadharma Inti Per","t":"CP","p":82.26,"q":null}],
  "PGJO": [{"n":"Pt Batu Investasi Indo","t":"CP","p":82.3,"q":null}],
  "BATA": [{"n":"Bafin (Nederland) B.V.","t":"OT","p":82.01,"q":null}],
  "PTIS": [{"n":"Straits Corporation Pt","t":"OT","p":81.82,"q":null}],
  "AMAN": [{"n":"Pt Griya Prima Amanda ","t":"OT","p":81.54,"q":null}],
  "TBIG": [{"n":"Bersama Digital Infras","t":"CP","p":81.29,"q":null}],
  "LPIN": [{"n":"Pt. Multipolar Tbk","t":"CP","p":81.71,"q":null}],
  "INAF": [{"n":"Pt Bio Farma (Persero)","t":"CP","p":80.66,"q":null}],
  "HALO": [{"n":"Hansen Jap","t":"ID","p":81.06,"q":null}],
  "LIFE": [{"n":"Mitsui Sumitomo Insura","t":"IS","p":80,"q":null}],
  "MINE": [{"n":"Pt Mitra Berkarya Suks","t":"CP","p":80.79,"q":null}],
  "SOSS": [{"n":"Pt. Alsok Bass Indones","t":"CP","p":79.83,"q":null}],
  "RSGK": [{"n":"Pt Sarana Meditama Met","t":"CP","p":79.84,"q":null}],
  "POLU": [{"n":"Pt Profashion Apparel","t":"CP","p":79.99,"q":null}],
  "RIGS": [{"n":"Pt. Surya Indah Muara ","t":"CP","p":80.54,"q":null}],
  "AMAG": [{"n":"Fairfax Asia Limited","t":"CP","p":80,"q":null}],
  "ICBP": [{"n":"Indofood Sukses Makmur","t":"CP","p":80.53,"q":null}],
  "RISE": [{"n":"Pt Tancorp Global Sent","t":"CP","p":80.3,"q":null}],
  "NETV": [{"n":"Pt Md Pictures Tbk","t":"CP","p":80.05,"q":null}],
  "RONY": [{"n":"Honour Accord Limited","t":"CP","p":80,"q":null}],
  "TAMU": [{"n":"Pt Andalan Lepas Panta","t":"CP","p":80,"q":null}],
  "PEVE": [{"n":"Tancorp Mega Buana Pt","t":"CP","p":80,"q":null}],
  "AUTO": [{"n":"Pt Astra International","t":"CP","p":80,"q":null}],
  "INPS": [{"n":"Pt. Surya Perkasa Sent","t":"CP","p":79.79,"q":null}],
  "KRAS": [{"n":"Perusahaan Perseroan (","t":"CP","p":80,"q":null}],
  "ERAL": [{"n":"Erajaya Swasembada Tbk","t":"CP","p":80,"q":null}],
  "FISH": [{"n":"Pt.Fks Corporindo Indo","t":"CP","p":79.06,"q":null}],
  "HRUM": [{"n":"Karunia Bara PerkasaP","t":"CP","p":79.79,"q":null}],
  "FAPA": [{"n":"Prinsep Management Lim","t":"CP","p":79.31,"q":null}],
  "RSCH": [{"n":"Pt. Wahyu Agung","t":"CP","p":79.43,"q":null}],
  "AALI": [{"n":"Pt Astra International","t":"CP","p":79.68,"q":null}],
  "BEER": [{"n":"Pt. Maju Minuman Minah","t":"CP","p":79.32,"q":null}],
  "FITT": [{"n":"Pt Jinlong Resources I","t":"CP","p":79.16,"q":null}],
  "ETWA": [{"n":"Pt Mordred Investama I","t":"CP","p":79.26,"q":null}],
  "SHID": [{"n":"Pt Empu Sahid Internat","t":"CP","p":78.97,"q":null}],
  "KINO": [{"n":"Pt. Kino Investindo","t":"CP","p":79,"q":null}],
  "FORE": [{"n":"Fore Holdings Pte. Ltd","t":"CP","p":78.92,"q":null}],
  "DKHH": [{"n":"Siliwangi Djajakusumah","t":"CP","p":79.21,"q":null}],
  "TIFA": [{"n":"The Korea Development ","t":"IB","p":77.5,"q":null}],
  "IRRA": [{"n":"Pt Global Dinamika Ken","t":"CP","p":78.78,"q":null}],
  "MGLV": [{"n":"Nextier Datamate Cente","t":"CP","p":78.74,"q":null}],
  "KDSI": [{"n":"Kitasubur Utama Pt","t":"CP","p":78.52,"q":null}],
  "BAIK": [{"n":"Anak Baik Sejahtera","t":"CP","p":78.84,"q":null}],
  "BESS": [{"n":"Pt Batulicin Enam Semb","t":"CP","p":78.36,"q":null}],
  "BELL": [{"n":"Pt Trisula Internation","t":"CP","p":78.13,"q":null}],
  "LIVE": [{"n":"Pt. Homeco Global Inve","t":"CP","p":78.69,"q":null}],
  "POLL": [{"n":"Pt Borneo Melawai Perk","t":"CP","p":78.14,"q":null}],
  "ACRO": [{"n":"Tae Sung Chung","t":"ID","p":78.4,"q":null}],
  "MHKI": [{"n":"Pt. Multi Hanna Sinerg","t":"CP","p":78.6,"q":null}],
  "PTPS": [{"n":"Pt. Sekawan Kontrindo","t":"CP","p":78.54,"q":null}],
  "IKPM": [{"n":"Pt Ikapharma Inti Mas","t":"CP","p":78.11,"q":null}],
  "KAQI": [{"n":"Pt. Tahtra Kertajaya I","t":"CP","p":78.32,"q":null}],
  "CLAY": [{"n":"Citra Putra Mandiri Pt","t":"OT","p":77.77,"q":null}],
  "RCCC": [{"n":"Pt. Gelora Rimba Jaya","t":"CP","p":77.92,"q":null}],
  "RLCO": [{"n":"Realco Omega Investama","t":"CP","p":77.6,"q":null}],
  "IPCM": [{"n":"Pt Pelindo Jasa Mariti","t":"OT","p":76.89,"q":null}],
  "FORU": [{"n":"Imr Asia Holding Pte L","t":"CP","p":76.81,"q":null}],
  "SIDO": [{"n":"Pt Hotel Candi Baru","t":"CP","p":77.59,"q":null}],
  "ASLC": [{"n":"Adi Sarana Armada Tbk ","t":"CP","p":77.6,"q":null}],
  "MTRA": [{"n":"Mitra Ditosam Indonesi","t":"OT","p":77.14,"q":null}],
  "AWAN": [{"n":"Rajati Alia Kapital Pt","t":"CP","p":76.62,"q":null}],
  "ASJT": [{"n":"Dana Pensun Perkebunan","t":"PF","p":77.39,"q":null}],
  "SWAT": [{"n":"Pt. Sumber Makmur Lumi","t":"CP","p":77.22,"q":null}],
  "FOOD": [{"n":"Super Capital Indonesi","t":"OT","p":76.92,"q":null}],
  "KING": [{"n":"Japarto Sukses Mandiri","t":"CP","p":76.84,"q":null}],
  "PPRE": [{"n":"Pt.Pembangunan Perumah","t":"CP","p":76.99,"q":null}],
  "MIDI": [{"n":"Sumber Alfaria Trijaya","t":"CP","p":77.09,"q":null}],
  "KARW": [{"n":"Saranakelola Investa","t":"CP","p":77.03,"q":null}],
  "ASGR": [{"n":"Pt Astra International","t":"CP","p":76.87,"q":null}],
  "TEBE": [{"n":"Pt. Dua Samudera Perka","t":"CP","p":76.91,"q":null}],
  "PURI": [{"n":"Pt. Bumi Kreasi Baru","t":"CP","p":76.8,"q":null}],
  "BELI": [{"n":"Pt Global Investama An","t":"CP","p":76.57,"q":null}],
  "GOLL": [{"n":"Jom Prawarsa Indonesia","t":"CP","p":76.42,"q":null}],
  "ADMF": [{"n":"Bank Danamon Indonesia","t":"IB","p":74.5,"q":null}],
  "POLA": [{"n":"Pt Pool Advista Indone","t":"CP","p":76.34,"q":null}],
  "PTMR": [{"n":"Mitra Pack Tbk","t":"CP","p":76.42,"q":null}],
  "HUMI": [{"n":"Pt Humpuss Intermoda T","t":"CP","p":76.43,"q":null}],
  "AYAM": [{"n":"Singgih Januratmoko","t":"ID","p":76.55,"q":null}],
  "MKAP": [{"n":"Pt. International Sawo","t":"CP","p":76,"q":null}],
  "TOOL": [{"n":"Pt Rohartindo Maju Per","t":"CP","p":76.1,"q":null}],
  "ATAP": [{"n":"Trimitra Prawara","t":"CP","p":76,"q":null}],
  "SMBR": [{"n":"Pt Semen Indonesia (Pe","t":"CP","p":75.51,"q":null}],
  "DAYA": [{"n":"Total Alliance Holding","t":"IB","p":73.87,"q":null}],
  "AMAR": [{"n":"Tolaram Pte. Ltd.","t":"CP","p":75.25,"q":null}],
  "NEST": [{"n":"Hoo Anton Siswanto","t":"ID","p":75.48,"q":null}],
  "SCMA": [{"n":"Pt Elang Mahkota Tekno","t":"CP","p":74.42,"q":null}],
  "BBSI": [{"n":"Pt Finaccel Teknologi ","t":"CP","p":75,"q":null}],
  "NIRO": [{"n":"Pt Mega Inti Perdana U","t":"CP","p":75.25,"q":null}],
  "MYTX": [{"n":"Indah Jaya Investama P","t":"CP","p":73.09,"q":null}],
  "KBRI": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":75.25,"q":null}],
  "PBID": [{"n":"Pt Alphen Internasiona","t":"CP","p":74.67,"q":null}],
  "URBN": [{"n":"Pt. Nusa Wijaya Proper","t":"CP","p":74.3,"q":null}],
  "MERK": [{"n":"Merck Holding Gmbh","t":"OT","p":73.99,"q":null}],
  "PKPK": [{"n":"Pt. Deli Putra Bangsa","t":"CP","p":75,"q":null}],
  "GEMA": [{"n":"Pt. Virucci Indogriya ","t":"CP","p":74.74,"q":null}],
  "MAPB": [{"n":"Mitra Adiperkasa Tbk","t":"CP","p":71.98,"q":null}],
  "BBSS": [{"n":"Agung Alam Anugrah Pt","t":"OT","p":72.92,"q":null}],
  "SAMF": [{"n":"Pt. Saraswanti Utama","t":"CP","p":74.27,"q":null}],
  "WSKT": [{"n":"Perusahaan Perseroan (","t":"CP","p":74.6,"q":null}],
  "PJAA": [{"n":"Pemerinta1H Daerah Dki","t":"OT","p":72,"q":null}],
  "SDPC": [{"n":"Pharmaniaga Internatio","t":"CP","p":73.43,"q":null}],
  "CBPE": [{"n":"Sandhi Parama Nusa","t":"CP","p":73.15,"q":null}],
  "SIMP": [{"n":"Indofood Agri Resource","t":"OT","p":73.46,"q":null}],
  "ASDM": [{"n":"Equity Development Inv","t":"CP","p":73.33,"q":null}],
  "KOPI": [{"n":"Pt. Mulya Tara Mandiri","t":"CP","p":72.86,"q":null}],
  "SOUL": [{"n":"Makna Prakarsa Utama ","t":"CP","p":73.21,"q":null}],
  "COWL": [{"n":"Pt Gama Nusapala","t":"CP","p":71.12,"q":null}],
  "TDPM": [{"n":"Dh Corporation Ltd","t":"CP","p":72.51,"q":null}],
  "ARCI": [{"n":"Pt Rajawali Corpora","t":"CP","p":71.89,"q":null}],
  "UFOE": [{"n":"Damai Sejahtera Lestar","t":"CP","p":72,"q":null}],
  "LABS": [{"n":"Optel Investama Mulia","t":"CP","p":72.39,"q":null}],
  "PTMP": [{"n":"Kencana Usaha Sentosa","t":"CP","p":72.51,"q":null}],
  "MTEL": [{"n":"Pt Telekomunikasi Indo","t":"CP","p":71.83,"q":null}],
  "SMGA": [{"n":"Sumber Global Energy T","t":"CP","p":72,"q":null}],
  "LINK": [{"n":"Axiata Investments (In","t":"IB","p":69.38,"q":null}],
  "BBRM": [{"n":"Pt. Marco Polo Indones","t":"CP","p":70.73,"q":null}],
  "VRNA": [{"n":"Mizuho Leasing Co Ltd","t":"IB","p":67.44,"q":null}],
  "VISI": [{"n":"David Dwiputra","t":"ID","p":71.54,"q":null}],
  "PRIM": [{"n":"I Nyoman Ehrich Lister","t":"ID","p":71.72,"q":null}],
  "WOMF": [{"n":"Pt Bank Maybank Indone","t":"IB","p":67.49,"q":null}],
  "RANC": [{"n":"Pt Global Digital Niag","t":"CP","p":70.56,"q":null}],
  "FASW": [{"n":"Siam Kraft Industry Co","t":"CP","p":59.85,"q":null}],
  "PNBS": [{"n":"Bank Pan Indonesia Tbk","t":"IB","p":67.3,"q":null}],
  "BRPT": [{"n":"Prajogo Pangestu","t":"ID","p":71.37,"q":null}],
  "KLAS": [{"n":"Kurnyatjan Sakti Efend","t":"ID","p":71.67,"q":null}],
  "SFAN": [{"n":"Pt Surya Fajar Corpora","t":"CP","p":71.24,"q":null}],
  "CBUT": [{"n":"Pt Sawit Sumbermas Sar","t":"CP","p":70.22,"q":null}],
  "IPCC": [{"n":"Pelindo Multi Terminal","t":"OT","p":71.28,"q":null}],
  "TIRT": [{"n":"Harita Jayaraya","t":"CP","p":71.13,"q":null}],
  "CPRI": [{"n":"Pt Rdw Global Investas","t":"OT","p":71.2,"q":null}],
  "WOOD": [{"n":"Pt Integra Indo Lestar","t":"CP","p":71.05,"q":null}],
  "MRAT": [{"n":"Mustika Ratu Investama","t":"CP","p":71.21,"q":null}],
  "BEEF": [{"n":"Asia Agri Internationa","t":"CP","p":70.59,"q":null}],
  "GRPM": [{"n":"Pt Prima Multi Usaha I","t":"CP","p":70.55,"q":null}],
  "GMFI": [{"n":"Pt Angkasa Pura Indone","t":"CP","p":65.77,"q":null}],
  "HRTA": [{"n":"Pt. Terang Anugrah Aba","t":"CP","p":71,"q":null}],
  "NICE": [{"n":"Energy Battery Indones","t":"CP","p":69.57,"q":null}],
  "SOFA": [{"n":"Pt Asia Investment Cap","t":"CP","p":70.97,"q":null}],
  "SMLE": [{"n":"Pt. Sinergi Asia Corpo","t":"CP","p":70.55,"q":null}],
  "VAST": [{"n":"Pt. Tembesu Elang Perk","t":"CP","p":69.98,"q":null}],
  "SAGE": [{"n":"Pt. Benteng Terang Sej","t":"CP","p":70,"q":null}],
  "MGNA": [{"n":"Pt Bhuwanatala Indah P","t":"CP","p":70.19,"q":null}],
  "SMMT": [{"n":"Pt Geo Energy Investam","t":"CP","p":67.24,"q":null}],
  "PGEO": [{"n":"Pertamina Power Indone","t":"CP","p":68.32,"q":null}],
  "DOOH": [{"n":"Pt. Prambanan Investas","t":"CP","p":70.3,"q":null}],
  "BCIC": [{"n":"J Trust Co Ltd","t":"CP","p":67.38,"q":null}],
  "GRPH": [{"n":"Pt. Mulia Jaya Palma","t":"CP","p":70.19,"q":null}],
  "BTPS": [{"n":"Pt Bank Smbc Indonesia","t":"IB","p":70,"q":null}],
  "AYLS": [{"n":"Pt Bintang Cahaya Inve","t":"CP","p":69.69,"q":null}],
  "TGUK": [{"n":"Pt Dinasti Kreatif Ind","t":"OT","p":69.33,"q":null}],
  "KEJU": [{"n":"Garudafood Putra Putri","t":"CP","p":66.07,"q":null}],
  "JRPT": [{"n":"Pt. Pembangunan Jaya","t":"CP","p":67.73,"q":null}],
  "DSFI": [{"n":"Pt Marina Berkah Inves","t":"CP","p":69.6,"q":null}],
  "DPUM": [{"n":"Pt Pandawa Putra Inves","t":"CP","p":69.2,"q":null}],
  "ISEA": [{"n":"Indo American Foods","t":"CP","p":69.24,"q":null}],
  "MKTR": [{"n":"Fuad Hasan Masyhur","t":"ID","p":68.62,"q":null}],
  "GGRM": [{"n":"Suryaduta Investama","t":"CP","p":69.29,"q":null}],
  "JSMR": [{"n":"Perusahaan Perseroan (","t":"CP","p":69.3,"q":null}],
  "WEGE": [{"n":"Perusahaan Perseroan (","t":"CP","p":69.3,"q":null}],
  "KMTR": [{"n":"Hsf (S) Pte Ltd","t":"CP","p":62.5,"q":null}],
  "HATM": [{"n":"Pt Habco Primatama","t":"CP","p":66.34,"q":null}],
  "GSMF": [{"n":"Equity Global Internat","t":"CP","p":68.28,"q":null}],
  "ENZO": [{"n":"Tritunggal Sukses Inve","t":"CP","p":68.56,"q":null}],
  "BPTR": [{"n":"Pt. Batavia Prosperind","t":"CP","p":67.4,"q":null}],
  "RATU": [{"n":"Rukun Raharja Tbk","t":"CP","p":68.77,"q":null}],
  "BBKP": [{"n":"Kookmin Bank Co. Ltd.","t":"CP","p":66.88,"q":null}],
  "INDR": [{"n":"Indorama Holdings B.V.","t":"OT","p":64.18,"q":null}],
  "ITIC": [{"n":"Djonny Saksono","t":"ID","p":68.36,"q":null}],
  "ZATA": [{"n":"Lembur Sadaya Investam","t":"CP","p":68.71,"q":null}],
  "POSA": [{"n":"Bintang Baja Hitam Pt","t":"CP","p":67.75,"q":null}],
  "MAPA": [{"n":"Mitra Adiperkasa Tbk","t":"CP","p":68.83,"q":null}],
  "JECC": [{"n":"Pt Monaspermata Persad","t":"CP","p":66.08,"q":null}],
  "SDMU": [{"n":"Tjoe Mien Sasminto","t":"ID","p":68.12,"q":null}],
  "PWON": [{"n":"Pt Pakuwon Arthaniaga","t":"CP","p":68.68,"q":null}],
  "CHEM": [{"n":"Pt Tunas Bahtera Harum","t":"CP","p":68.47,"q":null}],
  "KLIN": [{"n":"Pt. Samico Capital Uta","t":"CP","p":65.56,"q":null}],
  "PAMG": [{"n":"Christopher Sumasto Tj","t":"ID","p":68.24,"q":null}],
  "BBLD": [{"n":"Pt. Sari Dasa Karsa","t":"CP","p":67.6,"q":null}],
  "CITA": [{"n":"Harita Jayaraya","t":"CP","p":60.46,"q":null}],
  "RAAM": [{"n":"Ram Jethmal Punjabi","t":"ID","p":67.5,"q":null}],
  "BREN": [{"n":"Pt Barito Pacific Tbk","t":"CP","p":64.14,"q":null}],
  "CBMF": [{"n":"Richiwa Sakti Indonesi","t":"CP","p":67.73,"q":null}],
  "PTSN": [{"n":"Abidin Fan","t":"ID","p":66.47,"q":null}],
  "ALMI": [{"n":"Pt Husin Investama","t":"CP","p":65.78,"q":null}],
  "EDGE": [{"n":"Digital Edge (Hong Kon","t":"CP","p":59.1,"q":null}],
  "WINR": [{"n":"Pt. Pemenang Nusantara","t":"CP","p":68.08,"q":null}],
  "OLIV": [{"n":"Pt Olive Power Invest","t":"CP","p":67.9,"q":null}],
  "CSIS": [{"n":"Pt Andalan Utama Binta","t":"CP","p":65.21,"q":null}],
  "WMPP": [{"n":"Tumiyana","t":"ID","p":66.95,"q":null}],
  "SURE": [{"n":"Pt Super Capital Indon","t":"OT","p":58.87,"q":null}],
  "SICO": [{"n":"Pt. Sigma Energy Utama","t":"CP","p":67.58,"q":null}],
  "LPPS": [{"n":"Bank Julius Baer Co. L","t":"CP","p":67.52,"q":null}],
  "EMDE": [{"n":"Cosmopolitan Persada D","t":"CP","p":66.78,"q":null}],
  "ALDO": [{"n":"Pt.Golden Arista Inter","t":"CP","p":67.04,"q":null}],
  "SILO": [{"n":"Sight Investment Compa","t":"CP","p":64.04,"q":null}],
  "LOPI": [{"n":"Pt Sentra Amanah Ventu","t":"CP","p":67.13,"q":null}],
  "MCOL": [{"n":"Edika Agung Mandiri Pt","t":"CP","p":61.2,"q":null}],
  "SEMA": [{"n":"Pt. Semacom Global Man","t":"CP","p":66.8,"q":null}],
  "MDLA": [{"n":"Hetty Soetikno Dra","t":"ID","p":65.94,"q":null}],
  "MBAP": [{"n":"Pt Wahana Sentosa Ceme","t":"CP","p":60,"q":null}],
  "INOV": [{"n":"Samudera Industri Pt","t":"CP","p":66.38,"q":null}],
  "PDES": [{"n":"Pt Panorama Sentrawisa","t":"CP","p":66.15,"q":null}],
  "CDIA": [{"n":"Pt Chandra Asri Pacifi","t":"CP","p":60,"q":null}],
  "PLAN": [{"n":"Wahana Tata Bangun","t":"OT","p":66.85,"q":null}],
  "MBTO": [{"n":"Marthana Megahayu Inti","t":"OT","p":66.82,"q":null}],
  "ISAT": [{"n":"Ooredoo Hutchison Asia","t":"OT","p":65.64,"q":null}],
  "HITS": [{"n":"Pt Investa Dharma Pute","t":"CP","p":50.57,"q":null}],
  "HDFA": [{"n":"Rubicon Investments Ho","t":"OT","p":55.23,"q":null}],
  "HERO": [{"n":"Mulgrave Corporation B","t":"OT","p":63.59,"q":null}],
  "SGRO": [{"n":"Agpa Pte. Ltd.","t":"CP","p":65.72,"q":null}],
  "TCID": [{"n":"Mandom Corporation","t":"CP","p":65.23,"q":null}],
  "ESTA": [{"n":"Pt. Esta Utama Corpora","t":"CP","p":62.61,"q":null}],
  "LCKM": [{"n":"Pt Lck Investama Prima","t":"CP","p":62.78,"q":null}],
  "JATI": [{"n":"Pt Jati Piranti Solusi","t":"OT","p":64,"q":null}],
  "BEKS": [{"n":"Banten Global Developm","t":"CP","p":66.11,"q":null}],
  "SUNI": [{"n":"Soe To Tie Lin","t":"ID","p":64.6,"q":null}],
  "PZZA": [{"n":"Sriboga Raturaya Pt","t":"CP","p":64.79,"q":null}],
  "SWID": [{"n":"Pt Saraswanti Utama","t":"OT","p":63.52,"q":null}],
  "PTBA": [{"n":"Perusahaan Perseroan (","t":"CP","p":65.93,"q":null}],
  "BKSL": [{"n":"Pt Sakti Generasi Perd","t":"CP","p":65.27,"q":null}],
  "PPRO": [{"n":"Pt Pp Persero Tbk","t":"OT","p":64.96,"q":null}],
  "HAJJ": [{"n":"Pt Madinah Iman Wisata","t":"CP","p":64.96,"q":null}],
  "MDKI": [{"n":"Emde Industri Investam","t":"CP","p":65.08,"q":null}],
  "LPGI": [{"n":"Hanwha General Insuran","t":"IS","p":61.5,"q":null}],
  "APLI": [{"n":"Pt Maco Amangraha","t":"CP","p":58.8,"q":null}],
  "CMPP": [{"n":"Airasia Aviation Group","t":"CP","p":46.25,"q":null}],
  "PSAT": [{"n":"Profitama Hasil Indah","t":"CP","p":60.35,"q":null}],
  "VICI": [{"n":"Pt. Sukses Sejati Seja","t":"CP","p":59.95,"q":null}],
  "MIKA": [{"n":"Pt Griya Insani Cakra ","t":"CP","p":64.65,"q":null}],
  "ITMG": [{"n":"Banpu Minerals (Singap","t":"CP","p":65.14,"q":null}],
  "BLTZ": [{"n":"Cgi Holdings Limited","t":"OT","p":51,"q":null}],
  "CASS": [{"n":"Roket Cipta Sentosa Pt","t":"CP","p":61,"q":null}],
  "TINS": [{"n":"Pt Mineral Industri In","t":"OT","p":65,"q":null}],
  "ANTM": [{"n":"Perusahaan Perseroan (","t":"CP","p":65,"q":null}],
  "LUCY": [{"n":"Pt Delta Wibawa Bersam","t":"CP","p":59.42,"q":null}],
  "SKRN": [{"n":"Pt Saga Investama Seda","t":"CP","p":59.75,"q":null}],
  "BRAM": [{"n":"Kordsa Teknik Tekstil ","t":"CP","p":61.59,"q":null}],
  "DART": [{"n":"Hartadi Angkosubroto","t":"ID","p":46.65,"q":null}],
  "NRCA": [{"n":"Pt Surya Semesta Inter","t":"CP","p":63.94,"q":null}],
  "ZBRA": [{"n":"Pt Trinity Healthcare","t":"CP","p":62.01,"q":null}],
  "PYFA": [{"n":"Rejuve Global Investme","t":"CP","p":64.02,"q":null}],
  "DOSS": [{"n":"Pt Sukses Investama In","t":"CP","p":62.97,"q":null}],
  "TLDN": [{"n":"Pt Teladan Resources","t":"CP","p":59.88,"q":null}],
  "DLTA": [{"n":"San Miguel Malaysia (L","t":"CP","p":58.33,"q":null}],
  "STRK": [{"n":"Barito Mas Sukses","t":"CP","p":61.87,"q":null}],
  "AKRA": [{"n":"Pt Arthakencana Rayata","t":"CP","p":63.71,"q":null}],
  "EMAS": [{"n":"Merdeka Copper Gold Tb","t":"CP","p":63.33,"q":null}],
  "AHAP": [{"n":"Pt Asuransi Central As","t":"IS","p":62.58,"q":null}],
  "BOLT": [{"n":"Pt Garuda Multi Invest","t":"CP","p":61.65,"q":null}],
  "NAYZ": [{"n":"Pt. Asia Intrainvesta","t":"CP","p":62,"q":null}],
  "SBMA": [{"n":"Pt Surya Biru Titilea ","t":"OT","p":62.91,"q":null}],
  "IRSX": [{"n":"Pt Matra Tri Abadi","t":"CP","p":63.44,"q":null}],
  "SAFE": [{"n":"Infiniti Wahana Pt","t":"CP","p":56.57,"q":null}],
  "DSSA": [{"n":"Pt Sinar Mas Tunggal","t":"CP","p":59.9,"q":null}],
  "IPTV": [{"n":"Pt Global Mediacom Tbk","t":"CP","p":62.77,"q":null}],
  "ASLI": [{"n":"Pt Wahana Konstruksi M","t":"CP","p":62.72,"q":null}],
  "BIPP": [{"n":"Safire Capital Pte.Ltd","t":"CP","p":61.62,"q":null}],
  "VOKS": [{"n":"Hengtong Optic Electri","t":"CP","p":54.67,"q":null}],
  "FWCT": [{"n":"Fortuna Anugrah Sumber","t":"CP","p":58.08,"q":null}],
  "BBHI": [{"n":"Pt Mega Corpora","t":"CP","p":60.88,"q":null}],
  "POLY": [{"n":"Damiano Investments B.","t":"CP","p":62.42,"q":null}],
  "CHEK": [{"n":"Optel Investama Mulia","t":"CP","p":60.5,"q":null}],
  "OPMS": [{"n":"Asian Perkasa Indostee","t":"CP","p":59.79,"q":null}],
  "DMAS": [{"n":"Pt Sumber Arusmulia","t":"CP","p":57.28,"q":null}],
  "CBRE": [{"n":"Pt Omudas Investment H","t":"CP","p":61.13,"q":null}],
  "GHON": [{"n":"Tower Bersama Infrastr","t":"CP","p":50.43,"q":null}],
  "AMOR": [{"n":"Ashmore Investment Man","t":"CP","p":60.04,"q":null}],
  "PALM": [{"n":"Pt Provident Capital I","t":"CP","p":58.02,"q":null}],
  "DKFT": [{"n":"Pt Jinsheng Mining","t":"CP","p":61.63,"q":null}],
  "AXIO": [{"n":"Pt Exa Nusa Persada","t":"CP","p":59.25,"q":null}],
  "POLI": [{"n":"Po Sun Kok","t":"ID","p":56.95,"q":null}],
  "BUVA": [{"n":"Nusantara Utama Invest","t":"CP","p":61.64,"q":null}],
  "PNSE": [{"n":"Pt. Istana Kuta Ratu P","t":"CP","p":55.7,"q":null}],
  "KSIX": [{"n":"Pt Badra Arta","t":"CP","p":58.84,"q":null}],
  "MCOR": [{"n":"China Construction Ban","t":"CP","p":60,"q":null}],
  "JKON": [{"n":"Pt. Pembangunan Jaya","t":"CP","p":60.89,"q":null}],
  "UCID": [{"n":"Unicharm Corporation","t":"OT","p":59.2,"q":null}],
  "PMUI": [{"n":"Rudy Susanto Wijaya Ka","t":"ID","p":56,"q":null}],
  "GWSA": [{"n":"Prima Permata Sejahter","t":"CP","p":56.25,"q":null}],
  "MYOH": [{"n":"St International Corpo","t":"OT","p":59.03,"q":null}],
  "PMJS": [{"n":"Pt. Pahalamas Sejahter","t":"OT","p":50.24,"q":null}],
  "MGRO": [{"n":"Pt Mahkota Global Inve","t":"CP","p":56.4,"q":null}],
  "MERI": [{"n":"Merry Riana Indonesia","t":"CP","p":57.96,"q":null}],
  "TOBA": [{"n":"Highland Strategic Hol","t":"CP","p":60.36,"q":null}],
  "LAJU": [{"n":"Ervin Niaga Abadi Pt","t":"OT","p":60.69,"q":null}],
  "AMFG": [{"n":"Agc Inc.","t":"CP","p":44.53,"q":null}],
  "TUGU": [{"n":"Pt Pertamina (Persero)","t":"CP","p":58.5,"q":null}],
  "MMIX": [{"n":"Pt. Multi Inti Usaha","t":"CP","p":59.99,"q":null}],
  "NPGF": [{"n":"Pt Atmaja Makmur Gemil","t":"CP","p":56.01,"q":null}],
  "NICK": [{"n":"Pt. Indovest Central","t":"CP","p":57.6,"q":null}],
  "BSIM": [{"n":"Pt Sinar Mas Multiarth","t":"CP","p":59.99,"q":null}],
  "TCPI": [{"n":"Sari Nusantara Gemilan","t":"OT","p":55,"q":null}],
  "CMNP": [{"n":"Bp2S Sg/Bnp Paribas Si","t":"OT","p":59.35,"q":null}],
  "AISA": [{"n":"Pt. Pangan Sejahtera I","t":"CP","p":58.47,"q":null}],
  "BALI": [{"n":"Pt Kharisma Cipta Towe","t":"CP","p":59.7,"q":null}],
  "TKIM": [{"n":"App Purinusa Ekapersad","t":"CP","p":59.67,"q":null}],
  "APII": [{"n":"Arita GlobalPt","t":"CP","p":57.84,"q":null}],
  "CLEO": [{"n":"Pt. Tancorp Global Aba","t":"CP","p":56.12,"q":null}],
  "HOKI": [{"n":"Pt Buyung Investama Ge","t":"CP","p":59.95,"q":null}],
  "BMSR": [{"n":"Chance Stand Finance L","t":"OT","p":59.11,"q":null}],
  "MPIX": [{"n":"Pt Madura Prima Invest","t":"CP","p":60,"q":null}],
  "WTON": [{"n":"Perusahaan Perseroan (","t":"CP","p":60,"q":null}],
  "CHIP": [{"n":"Karya Permata Berkat J","t":"CP","p":59.61,"q":null}],
  "TRON": [{"n":"Daya Kemilau Nusantara","t":"CP","p":59.77,"q":null}],
  "ACES": [{"n":"Pt Kawan Lama Sejahter","t":"CP","p":60,"q":null}],
  "CNMA": [{"n":"Pt. Harkatjaya Bumiper","t":"CP","p":53.99,"q":null}],
  "INTD": [{"n":"Peak Aim Development L","t":"CP","p":54.74,"q":null}],
  "SPMA": [{"n":"Pt Pacific Star Synerg","t":"CP","p":49.98,"q":null}],
  "KETR": [{"n":"Pt Fajar Sejahtera Man","t":"CP","p":56.53,"q":null}],
  "AMIN": [{"n":"Sphere Corporation Sdn","t":"CP","p":58.39,"q":null}],
  "ZYRX": [{"n":"Timothy Siddik Shu","t":"ID","p":56.41,"q":null}],
  "LSIP": [{"n":"Pt Salim Ivomas Pratam","t":"CP","p":59.51,"q":null}],
  "GEMS": [{"n":"Pt Dian Swastatika Sen","t":"CP","p":51,"q":null}],
  "UNTR": [{"n":"Pt Astra International","t":"CP","p":59.5,"q":null}],
  "MEDS": [{"n":"Jemmy Kurniawan","t":"ID","p":59.67,"q":null}],
  "TRGU": [{"n":"Sunterra Indonesia Pt","t":"CP","p":51.05,"q":null}],
  "ABMM": [{"n":"Pt Tiara Marga Trakind","t":"CP","p":53.56,"q":null}],
  "PBSA": [{"n":"Pt Ascend Bangun Persa","t":"CP","p":46.16,"q":null}],
  "TRIL": [{"n":"Pt Arthabuana Karya Ma","t":"CP","p":57.54,"q":null}],
  "SRIL": [{"n":"Pt Huddleston Indonesi","t":"CP","p":59.03,"q":null}],
  "LRNA": [{"n":"Lorena","t":"CP","p":57.14,"q":null}],
  "MEGA": [{"n":"Pt Mega Corpora","t":"CP","p":58.02,"q":null}],
  "CTBN": [{"n":"Kestrel Wave Investmen","t":"CP","p":48.23,"q":null}],
  "INET": [{"n":"Pt Abadi Kreasi Unggul","t":"CP","p":59.38,"q":null}],
  "PRDA": [{"n":"Pt. Prodia Utama","t":"CP","p":57,"q":null}],
  "SOLA": [{"n":"Energi Hijau Investama","t":"CP","p":57.8,"q":null}],
  "PNBN": [{"n":"Pt. Panin Financial Tb","t":"CP","p":44.43,"q":null}],
  "JMAS": [{"n":"Koperasi Simpan Pinjam","t":"OT","p":57.95,"q":null}],
  "BLOG": [{"n":"Pt Sigmantara Alfindo","t":"CP","p":50.83,"q":null}],
  "KMDS": [{"n":"Pt Dima Investindo","t":"CP","p":55,"q":null}],
  "ISSP": [{"n":"Pt Cakra Bhakti Para P","t":"CP","p":57.69,"q":null}],
  "AMMS": [{"n":"Radiant Ruby Company L","t":"CP","p":51,"q":null}],
  "CRSN": [{"n":"Sheila Maria Tiwan","t":"ID","p":50.04,"q":null}],
  "ENAK": [{"n":"Barokah Melayu Food Pt","t":"CP","p":54.52,"q":null}],
  "ULTJ": [{"n":"Sabana Prawira Widjaja","t":"ID","p":53.17,"q":null}],
  "GLVA": [{"n":"Pt. Elsiscom Prima Kar","t":"CP","p":57.32,"q":null}],
  "BRIS": [{"n":"Pt Bank Mandiri","t":"IB","p":51.47,"q":null}],
  "TIRA": [{"n":"Pt Widjajatunggal Seja","t":"CP","p":44.12,"q":null}],
  "SHIP": [{"n":"Pt Goldenheaven Prima ","t":"CP","p":44.85,"q":null}],
  "STTP": [{"n":"Shindo Tiara Tunggal","t":"CP","p":56.76,"q":null}],
  "RALS": [{"n":"Pt. Ramayana Lestari S","t":"CP","p":55.88,"q":null}],
  "BMHS": [{"n":"Pt. Bunda Investama In","t":"CP","p":57.37,"q":null}],
  "MPMX": [{"n":"Saratoga Investama Sed","t":"CP","p":57.67,"q":null}],
  "OCAP": [{"n":"Uob Kay Hian (Hong Kon","t":"SC","p":45,"q":null}],
  "SMDR": [{"n":"Samudera Indonesia Tan","t":"OT","p":56.08,"q":null}],
  "PPGL": [{"n":"Darmawan Suryadi Sm","t":"ID","p":53.12,"q":null}],
  "SSTM": [{"n":"Sunsonindo Textile Inv","t":"OT","p":40.99,"q":null}],
  "RMKE": [{"n":"Pt Rmk Investama","t":"CP","p":56.8,"q":null}],
  "KOCI": [{"n":"Pt Exa Nusa Persada","t":"CP","p":49.33,"q":null}],
  "MAIN": [{"n":"Dragon Amity Pte Ltd","t":"CP","p":57.27,"q":null}],
  "IBFN": [{"n":"Pt. Intraco Penta . Tb","t":"CP","p":55.07,"q":null}],
  "WIDI": [{"n":"Bernard Widianto","t":"ID","p":57.77,"q":null}],
  "TOTL": [{"n":"Total Inti Persada","t":"CP","p":56.5,"q":null}],
  "IFSH": [{"n":"Pt Fajar Mining Resour","t":"OT","p":40.8,"q":null}],
  "IFII": [{"n":"Adrindo Intiperkasa P","t":"CP","p":51,"q":null}],
  "LTLS": [{"n":"Jpmcb Na Re-Pt Caturka","t":"CP","p":56.59,"q":null}],
  "PORT": [{"n":"China Merchants Intern","t":"CP","p":51,"q":null}],
  "BNII": [{"n":"Sorak Financial Holdin","t":"CP","p":45.02,"q":null}],
  "BSSR": [{"n":"Pt Wahana Sentosa Ceme","t":"CP","p":50,"q":null}],
  "SONA": [{"n":"Dfs Venture Singapore ","t":"CP","p":45,"q":null}],
  "GOLD": [{"n":"Tower Bersama Infrastr","t":"CP","p":51.09,"q":null}],
  "PGAS": [{"n":"Pt Pertamina (Persero)","t":"CP","p":56.96,"q":null}],
  "DATA": [{"n":"Verah Wahyudi S Wong","t":"ID","p":40.09,"q":null}],
  "PRAY": [{"n":"Pt. Famon Obor Maju","t":"CP","p":46.47,"q":null}],
  "NZIA": [{"n":"Richard Rachmadi Wiria","t":"OT","p":44.5,"q":null}],
  "SSMS": [{"n":"Pt.Citra Borneo Indah","t":"CP","p":53.75,"q":null}],
  "ADMG": [{"n":"Provestment Limited","t":"OT","p":49.51,"q":null}],
  "PSGO": [{"n":"Pt Jalinankasih Sesama","t":"CP","p":43.4,"q":null}],
  "BSBK": [{"n":"Clarissa Ady Sumasto T","t":"ID","p":39.85,"q":null}],
  "MANG": [{"n":"Mohamad Reza Pahlevi","t":"ID","p":54.56,"q":null}],
  "CPIN": [{"n":"Charoen Pokphand Indon","t":"CP","p":55.53,"q":null}],
  "PGUN": [{"n":"Pt Araya Agro Lestari","t":"CP","p":38.44,"q":null}],
  "MASB": [{"n":"Danabina Sentana","t":"CP","p":52.67,"q":null}],
  "CSMI": [{"n":"Lisa Muchtar","t":"ID","p":56.15,"q":null}],
  "BRNA": [{"n":"Pt Dwi Satrya Utama","t":"CP","p":54.57,"q":null}],
  "FUJI": [{"n":"Bank Julius Baer And C","t":"IB","p":55,"q":null}],
  "BAUT": [{"n":"Na Fasteners Pte Ltd","t":"CP","p":54.16,"q":null}],
  "OMRE": [{"n":"First Pacific Capital ","t":"CP","p":43.99,"q":null}],
  "NAIK": [{"n":"Pt Adiwarna Anugerah I","t":"CP","p":54.53,"q":null}],
  "JSPT": [{"n":"Pt Jan Darmadi Investi","t":"CP","p":50.95,"q":null}],
  "KBAG": [{"n":"Pt Visi Kota Indonesia","t":"CP","p":55.47,"q":null}],
  "BACA": [{"n":"Pt. Capital Global Inv","t":"CP","p":50.66,"q":null}],
  "FAST": [{"n":"Pt Gelael Pratama","t":"CP","p":41.18,"q":null}],
  "GDST": [{"n":"Gwie Gunato Gunawan","t":"ID","p":39.13,"q":null}],
  "JPFA": [{"n":"Japfa Ltd","t":"CP","p":55.43,"q":null}],
  "MEDC": [{"n":"Pt. Medco Daya Abadi L","t":"CP","p":51.5,"q":null}],
  "VERN": [{"n":"Pie Titin Suryani","t":"ID","p":46.63,"q":null}],
  "TOSK": [{"n":"Seiko Manito","t":"ID","p":54.17,"q":null}],
  "MSJA": [{"n":"Maju Selaras Jayamerta","t":"CP","p":53.21,"q":null}],
  "AEGS": [{"n":"J Suwanta Sinarya Dr","t":"ID","p":55.23,"q":null}],
  "ERAA": [{"n":"Eralink International ","t":"CP","p":55.17,"q":null}],
  "DFAM": [{"n":"Pt. Dafam","t":"CP","p":53.43,"q":null}],
  "TRUE": [{"n":"Pt Agung Perkasa Inves","t":"CP","p":52.83,"q":null}],
  "FMII": [{"n":"Pt Surya Mega Investin","t":"CP","p":46.67,"q":null}],
  "CMRY": [{"n":"Bambang Sutantio","t":"ID","p":53.56,"q":null}],
  "DGNS": [{"n":"Pt Bundamedik","t":"CP","p":39.2,"q":null}],
  "TBMS": [{"n":"The Furukawa Electric ","t":"CP","p":42.42,"q":null}],
  "IMAS": [{"n":"Gallant Venture Ltd","t":"CP","p":49.49,"q":null}],
  "PADA": [{"n":"Pt Sinergi Inti Andala","t":"CP","p":53.57,"q":null}],
  "MOLI": [{"n":"Pt Cropsco Panen Indon","t":"CP","p":52.15,"q":null}],
  "BABP": [{"n":"Pt Mnc Kapital Indones","t":"CP","p":48.85,"q":null}],
  "HEXA": [{"n":"Hitachi Construction M","t":"CP","p":48.59,"q":null}],
  "BBCA": [{"n":"Pt Dwimuria Investama ","t":"CP","p":54.94,"q":null}],
  "AGAR": [{"n":"Pt. Indo Kreasi Pratam","t":"CP","p":45,"q":null}],
  "PART": [{"n":"Cipta Investama Lancar","t":"CP","p":53.22,"q":null}],
  "WEHA": [{"n":"Pt Panorama Sentrawisa","t":"CP","p":52.48,"q":null}],
  "SRAJ": [{"n":"Pt Surya Cipta Inti Ce","t":"CP","p":50.27,"q":null}],
  "CINT": [{"n":"Pt.Tritirta Inti Mandi","t":"CP","p":53.26,"q":null}],
  "WIFI": [{"n":"Pt. Investasi Sukses B","t":"CP","p":54.42,"q":null}],
  "PNLF": [{"n":"Pt Paninvest Tbk","t":"CP","p":52.47,"q":null}],
  "HOMI": [{"n":"Pt. Graha Mulia Indota","t":"CP","p":52,"q":null}],
  "MITI": [{"n":"Pt. Prime Asia Capital","t":"CP","p":45.15,"q":null}],
  "CSRA": [{"n":"Pt. Verdan Sawit Lesta","t":"CP","p":38,"q":null}],
  "DGIK": [{"n":"Pt Global Dinamika Ken","t":"CP","p":52.3,"q":null}],
  "SMRU": [{"n":"Trada Alam Minera Tbk","t":"CP","p":52.3,"q":null}],
  "INTP": [{"n":"Heidelberg Materials A","t":"CP","p":53.4,"q":null}],
  "HOTL": [{"n":"Pt Tiara Realty","t":"CP","p":51.32,"q":null}],
  "LPLI": [{"n":"Bank Julius Baer Co. L","t":"CP","p":50.6,"q":null}],
  "SQMI": [{"n":"Wilton Resources Holdi","t":"CP","p":48.9,"q":null}],
  "KICI": [{"n":"Pt Kedawung Subur","t":"CP","p":43.62,"q":null}],
  "CANI": [{"n":"Pt. Anugrah Semesta La","t":"CP","p":39,"q":null}],
  "CASA": [{"n":"Pt Capital Strategic I","t":"CP","p":52.67,"q":null}],
  "PGLI": [{"n":"Pt Alami Lestari Inves","t":"CP","p":46.82,"q":null}],
  "KBLM": [{"n":"Pt. Sibalec","t":"CP","p":40.27,"q":null}],
  "SMIL": [{"n":"Hadi Suhermin","t":"ID","p":46.99,"q":null}],
  "GTBO": [{"n":"Green River Pte Ltd","t":"CP","p":33.39,"q":null}],
  "CTRA": [{"n":"Pt. Sang Pelopor","t":"CP","p":53.31,"q":null}],
  "BLES": [{"n":"Global Base Universal","t":"CP","p":40.83,"q":null}],
  "SAPX": [{"n":"Pt Satria Investama Pe","t":"CP","p":46.56,"q":null}],
  "WINE": [{"n":"Ida Bagus Rai Budarsa","t":"ID","p":37.5,"q":null}],
  "KJEN": [{"n":"Grafi1Ndo Karya Nusant","t":"OT","p":52.5,"q":null}],
  "GRIA": [{"n":"Khufran Hakim Noor","t":"ID","p":47.27,"q":null}],
  "SCNP": [{"n":"Sena Dwimakmur","t":"CP","p":45,"q":null}],
  "NFCX": [{"n":"Pt. Kresna Asset Manag","t":"CP","p":51.29,"q":null}],
  "PSSI": [{"n":"Pt Indoprima Marine","t":"CP","p":43.83,"q":null}],
  "BDKR": [{"n":"Tan John Tanuwijaya","t":"ID","p":51.01,"q":null}],
  "TGKA": [{"n":"Penta Widjaja Investin","t":"CP","p":36.21,"q":null}],
  "CARE": [{"n":"Pt Metro Healthcare In","t":"CP","p":49.92,"q":null}],
  "TPMA": [{"n":"Pt Dwitunggal Perkasa ","t":"CP","p":52.04,"q":null}],
  "OBMD": [{"n":"Pt Indotek Driling Sol","t":"CP","p":51.07,"q":null}],
  "BWPT": [{"n":"Cs Ag Sg Br S/A Pt Raj","t":"CP","p":37.7,"q":null}],
  "MAGP": [{"n":"Pt. Santika Griya Pers","t":"CP","p":50,"q":null}],
  "DYAN": [{"n":"Pt Teletransmedia","t":"CP","p":51.47,"q":null}],
  "VICO": [{"n":"Pt Gratamulia Pratama","t":"CP","p":45.06,"q":null}],
  "DPNS": [{"n":"Dutapermana MakmurPt","t":"CP","p":51.18,"q":null}],
  "ASPI": [{"n":"Andalan Sakti Inti","t":"CP","p":51.18,"q":null}],
  "GULA": [{"n":"Pt. Aman Resources Ind","t":"CP","p":51.65,"q":null}],
  "SGER": [{"n":"Pt Sumbermas Inti Ener","t":"CP","p":50.08,"q":null}],
  "RBMS": [{"n":"Richard R Wiriahardja","t":"ID","p":51.88,"q":null}],
  "CFIN": [{"n":"Bank Pan Indonesia Tbk","t":"IB","p":51.49,"q":null}],
  "HYGN": [{"n":"Hendrik Yong","t":"ID","p":47.52,"q":null}],
  "NTBK": [{"n":"Pt. Reborn Capital","t":"CP","p":51.85,"q":null}],
  "SRTG": [{"n":"Edwin Soeryadjaya","t":"ID","p":35.88,"q":null}],
  "PSDN": [{"n":"Pt Prasidha","t":"CP","p":47,"q":null}],
  "ASPR": [{"n":"Alex  Yoe","t":"ID","p":47.64,"q":null}],
  "PTDU": [{"n":"Pt Teknindo Geosistem ","t":"CP","p":41.67,"q":null}],
  "CLPI": [{"n":"Pt. Ink Color Int Pte.","t":"CP","p":51,"q":null}],
  "IMPC": [{"n":"Tunggal Jaya Investama","t":"CP","p":37.81,"q":null}],
  "HDIT": [{"n":"Pt Davest Investama Ma","t":"CP","p":52.25,"q":null}],
  "NICL": [{"n":"Pam Metalindo Pt","t":"CP","p":43.23,"q":null}],
  "MSIN": [{"n":"Pt.Media Nusantara Cit","t":"OT","p":50.02,"q":null}],
  "IOTF": [{"n":"Alamsyah","t":"ID","p":48.3,"q":null}],
  "IDEA": [{"n":"Eko Desriyanto","t":"ID","p":37.91,"q":null}],
  "BMRI": [{"n":"Perusahaan Perseroan (","t":"CP","p":51.48,"q":null}],
  "TAMA": [{"n":"Lancartama Tirta Angga","t":"CP","p":50.33,"q":null}],
  "COCO": [{"n":"Mahogany Global Invest","t":"CP","p":51.32,"q":null}],
  "BANK": [{"n":"Pt Aladin Global Ventu","t":"CP","p":50.82,"q":null}],
  "TLKM": [{"n":"Perusahaan Perseroan (","t":"CP","p":51.57,"q":null}],
  "BFIN": [{"n":"Trinugraha Capital And","t":"OT","p":51.12,"q":null}],
  "PTRO": [{"n":"Pt. Kreasi Jasa Persad","t":"CP","p":45.33,"q":null}],
  "BTON": [{"n":"Gwie Gunadi Gunawan","t":"ID","p":35.94,"q":null}],
  "LAPD": [{"n":"Pt Jsi Sinergi Mas","t":"CP","p":51,"q":null}],
  "ELSA": [{"n":"Pt Pertamina Hulu Ener","t":"CP","p":51.1,"q":null}],
  "MBMA": [{"n":"Merdeka Energi Nusanta","t":"CP","p":50.04,"q":null}],
  "BJTM": [{"n":"Pemda Tingkat I Provin","t":"OT","p":51.13,"q":null}],
  "SMSM": [{"n":"Pt Adrindo Inti Perkas","t":"CP","p":50.54,"q":null}],
  "MAPI": [{"n":"Pt Satya Mulia Gema Ge","t":"CP","p":51,"q":null}],
  "JAYA": [{"n":"Prima Globalindo Logis","t":"CP","p":45.79,"q":null}],
  "DNET": [{"n":"Hannawell Group Limite","t":"CP","p":39.35,"q":null}],
  "PTPP": [{"n":"Perusahaan Perseroan (","t":"CP","p":51,"q":null}],
  "YOII": [{"n":"Adi Wibowo Adisaputro","t":"ID","p":42.3,"q":null}],
  "LAND": [{"n":"Pt. Graha Mulia Indota","t":"CP","p":36.88,"q":null}],
  "DWGL": [{"n":"Hawthorn-Capital Inves","t":"OT","p":48.52,"q":null}],
  "KDTN": [{"n":"Putrasakti Mandiri Pt","t":"CP","p":38.12,"q":null}],
  "AGII": [{"n":"Pt Samator","t":"CP","p":35.24,"q":null}],
  "AMRT": [{"n":"Pt Sigmantara Alfindo","t":"CP","p":50.19,"q":null}],
  "MPPA": [{"n":"Pt. Multipolar Tbk","t":"CP","p":50.14,"q":null}],
  "LMPI": [{"n":"Hidayat Alim","t":"ID","p":38.24,"q":null}],
  "SMGR": [{"n":"Perusahaan Perseroan (","t":"CP","p":50.69,"q":null}],
  "MICE": [{"n":"Pt. Buana Graha Utama","t":"CP","p":48.34,"q":null}],
  "GJTL": [{"n":"Denham Pte Ltd","t":"CP","p":49.5,"q":null}],
  "PUDP": [{"n":"Pt. Istana Kuta Ratu P","t":"CP","p":44.54,"q":null}],
  "HBAT": [{"n":"Hendra Sutanto","t":"ID","p":44.94,"q":null}],
  "JTPE": [{"n":"Pt. Jasuindo Multi Inv","t":"CP","p":45.67,"q":null}],
  "KBLI": [{"n":"Pt.Omedata Electronics","t":"CP","p":49.47,"q":null}],
  "ANDI": [{"n":"Central Energi Pratama","t":"CP","p":49.73,"q":null}],
  "AREA": [{"n":"Pt. Dwi Tunggal Putra","t":"CP","p":38.06,"q":null}],
  "DRMA": [{"n":"Dharma Inti Anugerah ","t":"CP","p":47.6,"q":null}],
  "IATA": [{"n":"Pt. Karya Pacific Inve","t":"CP","p":48.79,"q":null}],
  "INDF": [{"n":"First Pacific Investme","t":"CP","p":50.07,"q":null}],
  "ASII": [{"n":"Jardine Cycle  And Car","t":"CP","p":50.11,"q":null}],
  "ISAP": [{"n":"Pt. Dua Putra Bersiner","t":"CP","p":50.39,"q":null}],
  "GTRA": [{"n":"Trimulti Adinata Perka","t":"CP","p":34.95,"q":null}],
  "TOTO": [{"n":"Toto Limited","t":"OT","p":36.6,"q":null}],
  "SOCI": [{"n":"Pt Pilar Sukses Utama","t":"CP","p":35.05,"q":null}],
  "MKPI": [{"n":"Pt.Karuna Paramita Pro","t":"CP","p":47.45,"q":null}],
  "PIPA": [{"n":"Pt Morris Capital Indo","t":"CP","p":49.92,"q":null}],
  "NASI": [{"n":"Piero Mustafa","t":"ID","p":42.24,"q":null}],
  "KOKA": [{"n":"Gao Jing","t":"ID","p":42.75,"q":null}],
  "TOWR": [{"n":"Pt Sapta Adhikari Inve","t":"CP","p":45.29,"q":null}],
  "MLIA": [{"n":"Pt. Eka Gunatama Mandi","t":"CP","p":41.45,"q":null}],
  "MARK": [{"n":"Tecable (Hk) Co. Limit","t":"OT","p":42.39,"q":null}],
  "MTPS": [{"n":"Central Energi Pratama","t":"CP","p":35.7,"q":null}],
  "BCAP": [{"n":"Pt. Mnc Asia Holding T","t":"CP","p":47.25,"q":null}],
  "AVIA": [{"n":"Pt Tancorp Surya Sento","t":"OT","p":36.6,"q":null}],
  "ASBI": [{"n":"Pt Srihana Utama","t":"CP","p":35.46,"q":null}],
  "DAAZ": [{"n":"Pt Daaz Nusantara Abad","t":"CP","p":42.49,"q":null}],
  "TYRE": [{"n":"Harris Muliawan","t":"ID","p":34.06,"q":null}],
  "SMMA": [{"n":"Sinar Mas Cakrawala","t":"CP","p":48.93,"q":null}],
  "WAPO": [{"n":"Hijau Sari Pt.","t":"CP","p":36.07,"q":null}],
  "INCO": [{"n":"Perusahaan Perseroan (","t":"CP","p":34,"q":null}],
  "BEST": [{"n":"Pt Argo Manunggal Land","t":"CP","p":48.13,"q":null}],
  "UANG": [{"n":"Sirius Surya Sentosa ","t":"CP","p":41,"q":null}],
  "TRIO": [{"n":"Sukses Perdana Prima ","t":"CP","p":38.25,"q":null}],
  "REAL": [{"n":"Enam Berlian Sinergi","t":"CP","p":46.72,"q":null}],
  "BNBA": [{"n":"Pt Takjub Finansial Te","t":"CP","p":33.45,"q":null}],
  "GPSO": [{"n":"Pt Pimsf Pulogadung","t":"CP","p":48.95,"q":null}],
  "MSTI": [{"n":"Jupri Wijaya","t":"ID","p":28.75,"q":null}],
  "BATR": [{"n":"Ridwan","t":"ID","p":44.05,"q":null}],
  "SOHO": [{"n":"Uob Kay Hian Private L","t":"SC","p":40.03,"q":null}],
  "TPIA": [{"n":"Barito Pacific Tbk","t":"CP","p":34.63,"q":null}],
  "MYOR": [{"n":"Unita Branindo","t":"OT","p":32.93,"q":null}],
  "FOLK": [{"n":"Pt Garam Ventura Indon","t":"CP","p":42.98,"q":null}],
  "BKDP": [{"n":"Adhibalaraja Pt.","t":"OT","p":34.6,"q":null}],
  "ATIC": [{"n":"Tis Inc","t":"CP","p":37.3,"q":null}],
  "ATLA": [{"n":"Rudi R. Sutantra","t":"ID","p":45.72,"q":null}],
  "ADRO": [{"n":"Adaro Strategic Invest","t":"CP","p":47.79,"q":null}],
  "OILS": [{"n":"Mandalindo Putra Perka","t":"CP","p":47.85,"q":null}],
  "GPRA": [{"n":"Pt Abadimukti Gunalest","t":"CP","p":47.5,"q":null}],
  "POWR": [{"n":"Pt. Udinda Wahanatama","t":"CP","p":30.48,"q":null}],
  "MORA": [{"n":"Pt Candrakarya Multikr","t":"CP","p":35.99,"q":null}],
  "HILL": [{"n":"Pt Hillcon Equity Mana","t":"CP","p":41.41,"q":null}],
  "INPP": [{"n":"Grahatama Kreasibaru","t":"CP","p":36.14,"q":null}],
  "RDTX": [{"n":"Sutiadi Widjaja","t":"ID","p":42.51,"q":null}],
  "CNTX": [{"n":"Pt Prospect Motor","t":"CP","p":34.2,"q":null}],
  "NANO": [{"n":"Nanotech Investama Sed","t":"CP","p":47.5,"q":null}],
  "LFLO": [{"n":"Ang Phek Tuan","t":"ID","p":32.57,"q":null}],
  "PSKT": [{"n":"Pt Basis Utama Prima","t":"CP","p":40.77,"q":null}],
  "TRAM": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":47.14,"q":null}],
  "FILM": [{"n":"Pt Md Corp Enterprises","t":"OT","p":44.12,"q":null}],
  "PANR": [{"n":"Pt Panorama Tirta Anug","t":"CP","p":44.9,"q":null}],
  "TOPS": [{"n":"Totalindo Investama Pe","t":"CP","p":47.39,"q":null}],
  "STAA": [{"n":"Pt Malibu Indah Lestar","t":"CP","p":36.69,"q":null}],
  "CYBR": [{"n":"Inv Management Pte Ltd","t":"CP","p":39.06,"q":null}],
  "BYAN": [{"n":"Low Tuck Kwong","t":"ID","p":40.22,"q":null}],
  "BIKA": [{"n":"Liliana Setiawan","t":"ID","p":33.92,"q":null}],
  "CSAP": [{"n":"Pt.Buanatata Adisentos","t":"CP","p":32.01,"q":null}],
  "ALII": [{"n":"Pt. Graha Adika Niaga","t":"CP","p":32.87,"q":null}],
  "IPOL": [{"n":"Jefflyne Golden Holdin","t":"CP","p":29.54,"q":null}],
  "NOBU": [{"n":"Hanwha Life Insurance ","t":"IS","p":40,"q":null}],
  "KKGI": [{"n":"Energy Collier Private","t":"CP","p":37.11,"q":null}],
  "MPOW": [{"n":"Phillip Securities Pte","t":"SC","p":44.8,"q":null}],
  "ARKO": [{"n":"Arkora Bakti Indonesia","t":"CP","p":38.89,"q":null}],
  "TFAS": [{"n":"Pt. Kresna Asset Manag","t":"CP","p":41.95,"q":null}],
  "PACK": [{"n":"Pt Eco Energi Perkasa","t":"CP","p":46.37,"q":null}],
  "PEGE": [{"n":"Rr Capital Group Pte. ","t":"CP","p":42.29,"q":null}],
  "INDY": [{"n":"Indika Inti Investindo","t":"CP","p":37.79,"q":null}],
  "BUKA": [{"n":"Kreatif Media Karya Pt","t":"CP","p":44.91,"q":null}],
  "OKAS": [{"n":"Pt. Multi Berkat Energ","t":"CP","p":38.69,"q":null}],
  "SKLT": [{"n":"Green Resources Invest","t":"OT","p":42.91,"q":null}],
  "BVIC": [{"n":"Pt. Victoria Investama","t":"CP","p":40.07,"q":null}],
  "ROCK": [{"n":"Luciana","t":"ID","p":27,"q":null}],
  "DMND": [{"n":"Chen Tsen Nan","t":"ID","p":34.93,"q":null}],
  "PTPW": [{"n":"Andreas Widhatama Kurn","t":"ID","p":36.2,"q":null}],
  "SCCO": [{"n":"Pt. Moda Sukses Makmur","t":"CP","p":33.6,"q":null}],
  "ECII": [{"n":"Uob Kay Hian Private L","t":"SC","p":29.78,"q":null}],
  "HELI": [{"n":"Pt Startel Communicati","t":"CP","p":30.25,"q":null}],
  "RAJA": [{"n":"Pt Sentosa Bersama Mit","t":"CP","p":35.25,"q":null}],
  "BUMI": [{"n":"Mach Energy (Hongkong)","t":"CP","p":45.78,"q":null}],
  "CPRO": [{"n":"Pt Central Pangan Prim","t":"CP","p":45.15,"q":null}],
  "ZONE": [{"n":"Verosito Gunawan","t":"ID","p":35.92,"q":null}],
  "SLIS": [{"n":"Pt Selis Investama Ind","t":"CP","p":45.67,"q":null}],
  "TRUK": [{"n":"Pt Guna Makmur Raya","t":"CP","p":40.17,"q":null}],
  "FUTR": [{"n":"Pt Aurora Dhana Nusant","t":"CP","p":45,"q":null}],
  "DIGI": [{"n":"Harvest Capital Intern","t":"CP","p":35.99,"q":null}],
  "DEPO": [{"n":"Pt Tancorp Surya Sukse","t":"CP","p":23.5,"q":null}],
  "ARGO": [{"n":"Argo Manunggal Land De","t":"OT","p":38.74,"q":null}],
  "ARKA": [{"n":"Pt. Arkha Tanto Prima","t":"CP","p":44.62,"q":null}],
  "CNKO": [{"n":"Anderson Bay Pte Ltd","t":"CP","p":45.59,"q":null}],
  "CCSI": [{"n":"Grahatama Kreasibaru","t":"CP","p":35.3,"q":null}],
  "TRIN": [{"n":"Pt Kunci Daud Indonesi","t":"CP","p":35.78,"q":null}],
  "TELE": [{"n":"Upaya Cipta Sejahtera ","t":"CP","p":37.32,"q":null}],
  "MSIE": [{"n":"Suzanna Rosa Prawiroma","t":"ID","p":30.14,"q":null}],
  "PICO": [{"n":"Pt Saranamulia Mahardh","t":"CP","p":32.04,"q":null}],
  "BAPI": [{"n":"Pt Grha Agung Properti","t":"OT","p":40.25,"q":null}],
  "MTSM": [{"n":"Yakin Wiskon","t":"CP","p":34.53,"q":null}],
  "BUAH": [{"n":"Hendro Susilo","t":"ID","p":36.5,"q":null}],
  "ITMA": [{"n":"Pt Astrindo Nusantara ","t":"CP","p":41.9,"q":null}],
  "EAST": [{"n":"Khalid Bin Omar Abdat","t":"ID","p":43.74,"q":null}],
  "MDIY": [{"n":"Mdih (Singapore) Pte. ","t":"CP","p":35.49,"q":null}],
  "INKP": [{"n":"App Purinusa Ekapersad","t":"CP","p":41.05,"q":null}],
  "ESIP": [{"n":"Pt Tanindo Omega Pasif","t":"CP","p":31.93,"q":null}],
  "BUKK": [{"n":"Solihin Jusuf Kalla","t":"ID","p":29.91,"q":null}],
  "MAXI": [{"n":"Pt Bintang Mulia Gemil","t":"CP","p":30.85,"q":null}],
  "IBOS": [{"n":"Pt. Goldman Investindo","t":"CP","p":42.6,"q":null}],
  "AADI": [{"n":"Adaro Strategic Invest","t":"CP","p":41.1,"q":null}],
  "MTMH": [{"n":"Sumatera Teknindo","t":"OT","p":32.56,"q":null}],
  "PDPP": [{"n":"Tirto Angesty","t":"ID","p":40,"q":null}],
  "AIMS": [{"n":"Pt Aims Indo Investama","t":"CP","p":31.16,"q":null}],
  "BUDI": [{"n":"Pt Budi Delta Swakarya","t":"CP","p":33.06,"q":null}],
  "INDX": [{"n":"Equatorex Sdn Bhd","t":"IB","p":38.11,"q":null}],
  "OBAT": [{"n":"Machmud Lutfi Huzain","t":"ID","p":31.6,"q":null}],
  "HADE": [{"n":"Pt. Maxima Financindo","t":"CP","p":43.26,"q":null}],
  "NASA": [{"n":"Pt Sinar Cemerlang Jay","t":"CP","p":42.71,"q":null}],
  "TAPG": [{"n":"Persada Capital Invest","t":"CP","p":33.07,"q":null}],
  "INCF": [{"n":"Alam Tulus Abadi Pt","t":"CP","p":40,"q":null}],
  "KKES": [{"n":"Catur Sentosa Adiprana","t":"CP","p":40.8,"q":null}],
  "ABBA": [{"n":"Pt. Beyond Media","t":"CP","p":40.47,"q":null}],
  "TRUS": [{"n":"Majujaya Terus Sejahte","t":"OT","p":30,"q":null}],
  "CASH": [{"n":"Andri Wijono Sutiono","t":"ID","p":33.8,"q":null}],
  "JIHD": [{"n":"Pt Kresna Aji Sembada","t":"CP","p":40.03,"q":null}],
  "EXCL": [{"n":"Axiata Investments (In","t":"IB","p":34.69,"q":null}],
  "HAIS": [{"n":"Nur Internasional Samu","t":"OT","p":40.8,"q":null}],
  "KAYU": [{"n":"Pt Darbe Putra Makmur","t":"CP","p":37.46,"q":null}],
  "TBLA": [{"n":"Pt Budi Delta Swakarya","t":"CP","p":32.77,"q":null}],
  "BRRC": [{"n":"Ari Sudarsono","t":"ID","p":42.42,"q":null}],
  "BLUE": [{"n":"Pt Cetak Biru Kapital","t":"CP","p":28.22,"q":null}],
  "NIKL": [{"n":"Nippon Steel Corporati","t":"CP","p":35,"q":null}],
  "SPTO": [{"n":"Multifortuna Asindo P","t":"CP","p":30,"q":null}],
  "MARI": [{"n":"Pt. Beyond Media","t":"CP","p":40.35,"q":null}],
  "BOAT": [{"n":"Sujaya Soekarno Putra","t":"ID","p":28.57,"q":null}],
  "NSSS": [{"n":"Pt Samuel Tumbuh Bersa","t":"CP","p":39.08,"q":null}],
  "MUTU": [{"n":"Sentra Mutu Handal","t":"CP","p":31.5,"q":null}],
  "FIRE": [{"n":"Aris Munandar","t":"ID","p":36,"q":null}],
  "BTEK": [{"n":"Golden Harvest Cocoa L","t":"CP","p":41.59,"q":null}],
  "TECH": [{"n":"Pt. Indosterling Saran","t":"CP","p":33.41,"q":null}],
  "FLMC": [{"n":"Theresia Indra Wirawan","t":"ID","p":39.49,"q":null}],
  "TFCO": [{"n":"Prospect Motor","t":"OT","p":33.08,"q":null}],
  "WMUU": [{"n":"Widodo Makmur Perkasa ","t":"CP","p":41.78,"q":null}],
  "WOWS": [{"n":"Pt. Ginting Jaya","t":"CP","p":42.44,"q":null}],
  "TNCA": [{"n":"Pt Akulaku Silvrr Indo","t":"CP","p":31.62,"q":null}],
  "INDO": [{"n":"Leslie Soemedi","t":"ID","p":32.21,"q":null}],
  "MDRN": [{"n":"Sungkono Honoris","t":"ID","p":35.23,"q":null}],
  "BGTG": [{"n":"Equity Development Inv","t":"CP","p":33.53,"q":null}],
  "AMMN": [{"n":"Pt Sumber Gemilang Per","t":"CP","p":32.17,"q":null}],
  "DCII": [{"n":"Otto Toto Sugiri","t":"ID","p":29.9,"q":null}],
  "LION": [{"n":"Lion Holdings Sdn Bhd","t":"CP","p":28.85,"q":null}],
  "WGSH": [{"n":"Walden Global Services","t":"CP","p":36.96,"q":null}],
  "DIVA": [{"n":"Asuransi Jiwa Kresna ","t":"IS","p":31.84,"q":null}],
  "ALTO": [{"n":"Pt Fikasa Bintang Ceme","t":"CP","p":36.44,"q":null}],
  "PANS": [{"n":"Pt. Patria Nusa Adamas","t":"CP","p":30,"q":null}],
  "ROTI": [{"n":"Pt. Indoritel Makmur I","t":"CP","p":25.77,"q":null}],
  "UVCR": [{"n":"Pt Trimegah Sumber Mas","t":"CP","p":41.22,"q":null}],
  "PMMP": [{"n":"Pt Tiga Makin Jaya","t":"CP","p":34.7,"q":null}],
  "RUNS": [{"n":"Sony Rachmadi Purnomo","t":"ID","p":29.04,"q":null}],
  "DEWI": [{"n":"Aditiya Fajar Junus","t":"ID","p":39,"q":null}],
  "BIKE": [{"n":"Henry Mulyadi","t":"ID","p":25.3,"q":null}],
  "KOTA": [{"n":"Dms Investama Pt","t":"CP","p":40.78,"q":null}],
  "JGLE": [{"n":"Pt Surya Global Nusant","t":"CP","p":38.76,"q":null}],
  "BSML": [{"n":"Pt Goldfive Investment","t":"CP","p":36.56,"q":null}],
  "ARNA": [{"n":"Tandean Rustandy","t":"ID","p":37.32,"q":null}],
  "KEEN": [{"n":"Paramata Indah Lestari","t":"CP","p":30.3,"q":null}],
  "PJHB": [{"n":"Hero Gozali","t":"ID","p":37.5,"q":null}],
  "SATU": [{"n":"Kota Satu Indonesia Pt","t":"OT","p":33.18,"q":null}],
  "BOBA": [{"n":"Hengky  Wijaya","t":"ID","p":28.88,"q":null}],
  "PEHA": [{"n":"Pt Kimia Farma (Perser","t":"CP","p":28.39,"q":null}],
  "GUNA": [{"n":"Tjokro Gunawan","t":"ID","p":24,"q":null}],
  "HGII": [{"n":"Sep International Neth","t":"CP","p":25,"q":null}],
  "ASRM": [{"n":"Syahril","t":"OT","p":31.51,"q":null}],
  "MTLA": [{"n":"Pt Metropolitan Persad","t":"CP","p":36.7,"q":null}],
  "UNIC": [{"n":"Aspirasi LuhurPt","t":"CP","p":36.35,"q":null}],
  "BAPA": [{"n":"Adicipta Griyasejati ","t":"CP","p":33.94,"q":null}],
  "MTDL": [{"n":"Ciputra Corpora. Pt","t":"CP","p":36.21,"q":null}],
  "MPRO": [{"n":"Jonathan Tahir","t":"ID","p":34.22,"q":null}],
  "SOTS": [{"n":"Herman Herry Adranacus","t":"ID","p":26,"q":null}],
  "BSDE": [{"n":"Paraga Artamida Pt","t":"OT","p":30.52,"q":null}],
  "BOLA": [{"n":"Pieter Tanuri","t":"ID","p":38.26,"q":null}],
  "RODA": [{"n":"Nio Yantony","t":"ID","p":26.52,"q":null}],
  "MNCN": [{"n":"Pt Global Mediacom Tbk","t":"CP","p":40.1,"q":null}],
  "CGAS": [{"n":"Pt Petro Asia Energy","t":"CP","p":32.32,"q":null}],
  "CRAB": [{"n":"Gindra Tardy","t":"ID","p":26.04,"q":null}],
  "TAYS": [{"n":"Anwar Tay","t":"ID","p":35.93,"q":null}],
  "SKBM": [{"n":"Tael Two Partners Ltd","t":"OT","p":32.06,"q":null}],
  "SNLK": [{"n":"Unilink Ventures Inc.","t":"CP","p":36.69,"q":null}],
  "SULI": [{"n":"Natureverse Inc. (Pte.","t":"CP","p":35.9,"q":null}],
  "KONI": [{"n":"Dasabina Adityasarana","t":"OT","p":31.26,"q":null}],
  "GZCO": [{"n":"Pt. Golden Zaga Indone","t":"CP","p":28.37,"q":null}],
  "LMAX": [{"n":"Kartiko Soemargono","t":"ID","p":33.25,"q":null}],
  "SINI": [{"n":"Pt. Autum Prima Indone","t":"CP","p":30,"q":null}],
  "BJBR": [{"n":"Pemda Provinsi Jawa Ba","t":"OT","p":38.52,"q":null}],
  "GGRP": [{"n":"Pt Apollo Visintama Pu","t":"CP","p":23.53,"q":null}],
  "DOID": [{"n":"Northstar Tambang Pers","t":"OT","p":38.22,"q":null}],
  "ARTO": [{"n":"Metamorfosis Ekosistem","t":"CP","p":29.79,"q":null}],
  "NUSA": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":38.01,"q":null}],
  "MEJA": [{"n":"Triple Berkah Bersama","t":"CP","p":39.31,"q":null}],
  "APEX": [{"n":"Pt Aserra Capital","t":"CP","p":31.76,"q":null}],
  "RAFI": [{"n":"Globalasia Capital Inv","t":"OT","p":38.36,"q":null}],
  "BCIP": [{"n":"Pt Bumi Citra Investin","t":"CP","p":38.07,"q":null}],
  "EURO": [{"n":"Timmsvale Pt","t":"CP","p":35.7,"q":null}],
  "PPRI": [{"n":"Philip Sumali","t":"ID","p":26.05,"q":null}],
  "MAHA": [{"n":"Edika Agung Mandiri Pt","t":"CP","p":34.5,"q":null}],
  "LUCK": [{"n":"Caroline Himawati Hida","t":"ID","p":29.2,"q":null}],
  "PNGO": [{"n":"Wilson Sutantio","t":"ID","p":22.76,"q":null}],
  "ELIT": [{"n":"Gratus Deo Indonesia ","t":"OT","p":27.42,"q":null}],
  "DEFI": [{"n":"Asuransi Jiwa Kresna ","t":"IS","p":23.57,"q":null}],
  "DMMX": [{"n":"Pt Nfc Indonesia Tbk","t":"CP","p":27.65,"q":null}],
  "MPXL": [{"n":"Ye Hun Ki","t":"ID","p":22,"q":null}],
  "GMTD": [{"n":"Makassar Permata Sulaw","t":"OT","p":32.5,"q":null}],
  "AKPI": [{"n":"Tiara Intimahkota","t":"OT","p":23.03,"q":null}],
  "TRIM": [{"n":"Garibaldi Thohir","t":"ID","p":34.68,"q":null}],
  "IKAN": [{"n":"Pt Berkah Delapan Samu","t":"CP","p":33.52,"q":null}],
  "UNTD": [{"n":"Tan Tjoe Ing","t":"ID","p":22.5,"q":null}],
  "PNIN": [{"n":"Paninkorp Pt","t":"OT","p":29.71,"q":null}],
  "BINA": [{"n":"Pt. Indolife Pensionta","t":"IS","p":21.83,"q":null}],
  "MLPL": [{"n":"Bank Julius Baer Co. L","t":"CP","p":32.13,"q":null}],
  "SBAT": [{"n":"Tan Heng Lok","t":"ID","p":34.48,"q":null}],
  "PTSP": [{"n":"Pt. Graha Sentosa Pers","t":"CP","p":27.63,"q":null}],
  "YELO": [{"n":"Pt Artalindo Semesta N","t":"CP","p":37.4,"q":null}],
  "SMRA": [{"n":"Pt Semarop Agung","t":"CP","p":35.8,"q":null}],
  "BBYB": [{"n":"Pt Akulaku Silvrr Indo","t":"CP","p":34.45,"q":null}],
  "UNIQ": [{"n":"Burhan Tjokro","t":"ID","p":22.52,"q":null}],
  "MINA": [{"n":"Pt Basis Utama Prima","t":"CP","p":30.48,"q":null}],
  "OASA": [{"n":"Gafur Sulistyo UmarIr","t":"ID","p":35.25,"q":null}],
  "TRIS": [{"n":"Pt. Inti Nusa Damai","t":"CP","p":20.16,"q":null}],
  "RUIS": [{"n":"Haiyanto","t":"ID","p":23.97,"q":null}],
  "HOPE": [{"n":"Pt. Harapan Group Suks","t":"CP","p":32.27,"q":null}],
  "IPPE": [{"n":"Lembur Sadaya Investam","t":"CP","p":35.22,"q":null}],
  "SPRE": [{"n":"Rizet Ramawi","t":"ID","p":27.83,"q":null}],
  "MAYA": [{"n":"Mayapada Karunia Pt","t":"OT","p":24.16,"q":null}],
  "PBRX": [{"n":"Trisetijo Manunggal Ut","t":"CP","p":31.07,"q":null}],
  "SUPA": [{"n":"Pt Elang Media Visitam","t":"CP","p":27.6,"q":null}],
  "JAST": [{"n":"Uob Kay Hian Private L","t":"SC","p":29.95,"q":null}],
  "GOOD": [{"n":"Hormel Foods Internati","t":"CP","p":30.17,"q":null}],
  "TOYS": [{"n":"Iwan Tirtha","t":"ID","p":28.86,"q":null}],
  "NINE": [{"n":"Poh Holdings Pte Ltd","t":"CP","p":35.85,"q":null}],
  "TMPO": [{"n":"Pt.Grafiti Pers","t":"CP","p":24.28,"q":null}],
  "ASRI": [{"n":"Pt. Tangerang Fajar In","t":"CP","p":25.72,"q":null}],
  "BNBR": [{"n":"Port Fraser Internatio","t":"CP","p":24.31,"q":null}],
  "EPAC": [{"n":"Pt Omni Multi Industri","t":"CP","p":24.22,"q":null}],
  "STAR": [{"n":"Calculus Investment Pt","t":"CP","p":32.19,"q":null}],
  "COAL": [{"n":"Sujaka Lays","t":"ID","p":34.89,"q":null}],
  "BMTR": [{"n":"Pt. Mnc Asia Holding T","t":"CP","p":34.32,"q":null}],
  "UDNG": [{"n":"Jose Loupiga Keliat","t":"ID","p":22.71,"q":null}],
  "KBLV": [{"n":"Pt Reksa Puspita Karya","t":"CP","p":33.76,"q":null}],
  "BISI": [{"n":"Agrindo Pratama","t":"CP","p":31,"q":null}],
  "TRST": [{"n":"Pt. K And L Capital","t":"CP","p":26.71,"q":null}],
  "VIVA": [{"n":"Pt. Bakrie Global Vent","t":"CP","p":32.94,"q":null}],
  "VTNY": [{"n":"Carta Holdings Co. Lt","t":"CP","p":21.06,"q":null}],
  "ARII": [{"n":"Pt. Calorie Viva Utama","t":"CP","p":29.08,"q":null}],
  "ARTI": [{"n":"Ratu Prabu Pt","t":"CP","p":33.06,"q":null}],
  "BAJA": [{"n":"Pandji Surya Soerjopra","t":"ID","p":16.47,"q":null}],
  "LPPF": [{"n":"Auric Digital Retail P","t":"CP","p":29.23,"q":null}],
  "WIIM": [{"n":"Indahtati Widjajadi","t":"ID","p":25.48,"q":null}],
  "INAI": [{"n":"Pt Husin Investama","t":"CP","p":29.22,"q":null}],
  "ASHA": [{"n":"Pt Asha Fortuna Corpor","t":"CP","p":30,"q":null}],
  "DSNG": [{"n":"Triputra Investindo Ar","t":"CP","p":28.33,"q":null}],
  "KIOS": [{"n":"Pt Artav Mobile Indone","t":"CP","p":32.56,"q":null}],
  "COIN": [{"n":"Megah Perkasa Investin","t":"CP","p":23.98,"q":null}],
  "BIRD": [{"n":"Pt. Pusaka Citra Djoko","t":"CP","p":28.37,"q":null}],
  "LEAD": [{"n":"Pt Jalan Terang Samudr","t":"CP","p":23.19,"q":null}],
  "KUAS": [{"n":"Grace Capital Investme","t":"OT","p":27.3,"q":null}],
  "BAYU": [{"n":"Pt. Graha Sentosa Pers","t":"CP","p":28.08,"q":null}],
  "INTA": [{"n":"Petrus Halim","t":"ID","p":22.93,"q":null}],
  "DGWG": [{"n":"David Yaory","t":"ID","p":30.09,"q":null}],
  "BEBS": [{"n":"Pt Berkah Global Inves","t":"CP","p":31.39,"q":null}],
  "LPKR": [{"n":"Bank Julius Baer Co. L","t":"CP","p":25.79,"q":null}],
  "RELF": [{"n":"Pt. Relife Property","t":"CP","p":19.44,"q":null}],
  "NATO": [{"n":"Pt Mercury Strategic I","t":"CP","p":26.87,"q":null}],
  "EMTK": [{"n":"Rd Eddy K Sariaatmadja","t":"ID","p":21.88,"q":null}],
  "LMSH": [{"n":"Lion Holdings Private ","t":"CP","p":25.55,"q":null}],
  "RGAS": [{"n":"Agus Salim","t":"ID","p":17.35,"q":null}],
  "BOGA": [{"n":"Gx Archipelago Pte.Ltd","t":"CP","p":29.5,"q":null}],
  "INCI": [{"n":"Tamzil Tanmizi","t":"ID","p":18.8,"q":null}],
  "ICON": [{"n":"Prof.Dr.Ir. Anastasia ","t":"OT","p":19.08,"q":null}],
  "ASSA": [{"n":"Adi Dinamika Investind","t":"CP","p":23.08,"q":null}],
  "VKTR": [{"n":"Bakrie & Brothers Tbk","t":"CP","p":24.4,"q":null}],
  "WINS": [{"n":"Wintermarjaya Lestari ","t":"CP","p":25.55,"q":null}],
  "ASMI": [{"n":"Asuransi Jiwa Kresna ","t":"IS","p":29.96,"q":null}],
  "SKYB": [{"n":"Jpmcb Na Re-Ora Pro No","t":"CP","p":18.37,"q":null}],
  "BMBL": [{"n":"Pt. Ammar Al Amanah","t":"CP","p":25.12,"q":null}],
  "BHAT": [{"n":"Pt Bhakti Artha Global","t":"CP","p":25.1,"q":null}],
  "GAMA": [{"n":"Pt.Gading Investments","t":"CP","p":24,"q":null}],
  "RICY": [{"n":"Spanola Holdings Ltd.","t":"OT","p":19.48,"q":null}],
  "MREI": [{"n":"Pt. Graha Sentosa Pers","t":"CP","p":20.53,"q":null}],
  "WSBP": [{"n":"Pt. Waskita Karya A/C ","t":"CP","p":28.21,"q":null}],
  "CITY": [{"n":"Pt Sakti Generasi Perd","t":"CP","p":20.63,"q":null}],
  "BRMS": [{"n":"Emirates Tarian Global","t":"OT","p":25.1,"q":null}],
  "PURE": [{"n":"Pt Trinitan Resourceta","t":"CP","p":26.45,"q":null}],
  "SRSN": [{"n":"Budhi Bersaudara Manun","t":"CP","p":14.15,"q":null}],
  "POOL": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":26.73,"q":null}],
  "KPIG": [{"n":"Pt. Mnc Asia Holding T","t":"CP","p":18.72,"q":null}],
  "PCAR": [{"n":"Perusahaan Perseroan (","t":"IS","p":26.19,"q":null}],
  "LABA": [{"n":"Pt Nev Stored Energy","t":"CP","p":25.54,"q":null}],
  "UNIT": [{"n":"Pt. Lenovo Worldwide C","t":"CP","p":21.78,"q":null}],
  "HOME": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":24.67,"q":null}],
  "ZINC": [{"n":"Sim Antony","t":"ID","p":14.42,"q":null}],
  "ARMY": [{"n":"Mandiri Mega Jaya Pt","t":"CP","p":20.46,"q":null}],
  "APIC": [{"n":"Pan Pacific Investama","t":"CP","p":20.27,"q":null}],
  "MTFN": [{"n":"Express Profitable Inv","t":"OT","p":21.1,"q":null}],
  "MKNT": [{"n":"Pt Monjess Investama","t":"CP","p":22.63,"q":null}],
  "CTTH": [{"n":"Parallax Venture Partn","t":"OT","p":18.9,"q":null}],
  "KRYA": [{"n":"Green City Sg Pte Ltd","t":"CP","p":21.77,"q":null}],
  "BTEL": [{"n":"Pt. Huawei Tech Invest","t":"CP","p":16.81,"q":null}],
  "DILD": [{"n":"Cgs International Secu","t":"IB","p":15.02,"q":null}],
  "MABA": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":16.62,"q":null}],
  "MDLN": [{"n":"Panin Sekuritas Tbk P","t":"SC","p":15.29,"q":null}],
  "ESSA": [{"n":"Chander Vinod Laroya","t":"ID","p":16.38,"q":null}],
  "SMKM": [{"n":"Lim Shrimp Org Pte. Lt","t":"CP","p":25,"q":null}],
  "BIPI": [{"n":"Pt Indotambang Perkasa","t":"CP","p":19.39,"q":null}],
  "MDKA": [{"n":"Saratoga Investama Sed","t":"CP","p":19.37,"q":null}],
  "MCAS": [{"n":"Pt. 1 Inti Dot Com","t":"CP","p":13.48,"q":null}],
  "KIJA": [{"n":"Mu Min Ali Gunawan","t":"ID","p":21.09,"q":null}],
  "ENRG": [{"n":"Pt Shima Global Kapita","t":"CP","p":17.42,"q":null}],
  "RIMO": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":18.18,"q":null}],
  "UNSP": [{"n":"Pt Bakrie Capital Indo","t":"CP","p":17.82,"q":null}],
  "KLBF": [{"n":"Pt Ladang Ira Panen","t":"CP","p":10.47,"q":null}],
  "TARA": [{"n":"Pt.Surya Buana Makmur","t":"CP","p":15.04,"q":null}],
  "FIMP": [{"n":"Pt. Bangun Bumi Utama","t":"CP","p":13.82,"q":null}],
  "IIKP": [{"n":"Perusahaan Perseroan (","t":"IS","p":15.22,"q":null}],
  "AKKU": [{"n":"Pt. Renaldijaya Ekaint","t":"CP","p":16.08,"q":null}],
  "JSKY": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":20.34,"q":null}],
  "PURA": [{"n":"Pt Rajawali Inti","t":"CP","p":15.28,"q":null}],
  "INPC": [{"n":"Pt Cakra Inti Utama","t":"CP","p":14.38,"q":null}],
  "BHIT": [{"n":"Ht Investment Developm","t":"CP","p":15.38,"q":null}],
  "KREN": [{"n":"Pt Kresna Prima Invest","t":"CP","p":14.57,"q":null}],
  "DADA": [{"n":"Pt Karya Permata Inova","t":"CP","p":21.53,"q":null}],
  "BLTA": [{"n":"Tunggaladhi Baskara P","t":"CP","p":17.41,"q":null}],
  "SSIA": [{"n":"Pt Dwimuria Investama ","t":"CP","p":10.24,"q":null}],
  "HEAL": [{"n":"Pt Astra Healthcare In","t":"CP","p":12.95,"q":null}],
  "MENN": [{"n":"Jora Nilam Judge","t":"ID","p":18.37,"q":null}],
  "BULL": [{"n":"Pt Delta Royal Sejahte","t":"CP","p":14.53,"q":null}],
  "SUGI": [{"n":"Asiaciti Trust Singapo","t":"OT","p":11.52,"q":null}],
  "IKAI": [{"n":"Mahkota Properti Indo ","t":"CP","p":19.34,"q":null}],
  "TGRA": [{"n":"Terregra Asia Equity ","t":"CP","p":16.46,"q":null}],
  "PLAS": [{"n":"Ubs Ag London","t":"IB","p":8.49,"q":null}],
  "YULE": [{"n":"Pt Yulie Sekuritas Ind","t":"SC","p":11.08,"q":null}],
  "BOSS": [{"n":"Pt Megah Prakarsa Utam","t":"CP","p":13.58,"q":null}],
  "MIRA": [{"n":"Pt. Inti  Kencana Pran","t":"CP","p":11.67,"q":null}],
  "DEWA": [{"n":"Goldwave Capital Limit","t":"OT","p":9.38,"q":null}],
  "SIMA": [{"n":"Jaksa Agung Muda Bidan","t":"OT","p":12.05,"q":null}],
  "LCGP": [{"n":"Perusahaan Perseroan (","t":"IS","p":6.57,"q":null}],
  "CARS": [{"n":"Pt Berjaya Trimakmur S","t":"CP","p":4.99,"q":null}],
  "RMKO": [{"n":"Pt Rmk Investama","t":"CP","p":15.4,"q":null}],
  "DUCK": [{"n":"Fidelity Funds","t":"MF","p":9.88,"q":null}],
  "DEAL": [{"n":"Pt. Bimada Paramita Ad","t":"CP","p":10.25,"q":null}],
  "GOTO": [{"n":"Svf Gt Subco (Singapor","t":"IB","p":7.65,"q":null}],
  "LMAS": [{"n":"Suparman Tjahaja","t":"ID","p":7.46,"q":null}],
  "HKMU": [{"n":"Pt Alam Mubarok Sejaht","t":"CP","p":4.87,"q":null}],
  "ENVY": [{"n":"Pt Envy Manajemen Kons","t":"OT","p":7.24,"q":null}],
  "ELTY": [{"n":"Asuransi Simas Jiwa","t":"IS","p":5.35,"q":null}],
  "TAXI": [{"n":"Robert","t":"ID","p":4.89,"q":null}],
  "PADI": [{"n":"Pt Sentosa Bersama Mit","t":"CP","p":5.75,"q":null}],
  "NCKL": [{"n":"Glencore International","t":"OT","p":6.5,"q":null}],
  "WIRG": [{"n":"Florensia Kartini Tedj","t":"ID","p":4.8,"q":null}],
  "BBTN": [{"n":"Pt Taspen (Persero)","t":"IS","p":4.95,"q":null}],
  "BBNI": [{"n":"Djs Ketenagakerjaan Pr","t":"IS","p":3.51,"q":null}],
  "BBRI": [{"n":"Indonesia Investment A","t":"OT","p":3.63,"q":null}],
  "ADHI": [{"n":"Panin Sekuritas Tbk P","t":"SC","p":2.68,"q":null}],
};
